// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { V1BadgeData } from "../types/badges";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";

export interface GetBadgeParams {
  user: string;
  interval:
    | "today"
    | "yesterday"
    | "week"
    | "month"
    | "year"
    | "7_days"
    | "last_7_days"
    | "30_days"
    | "last_30_days"
    | "6_months"
    | "last_6_months"
    | "12_months"
    | "last_12_months"
    | "last_year"
    | "any"
    | "all_time"
    | (string & {});
  filter: string;
}

/**
 * Retrieves badge data for a user, interval, and filter in a format compatible with Shields.io. Use `interval` to choose the aggregation period and `filter` to select an entity such as a project or language; public data access must be enabled for the user.
 *
 * Retrieve total time for a given entity (e.g. a project) within a given range (e.g. one week) in a format compatible with [Shields.io](https://shields.io/endpoint). Requires public data access to be allowed.
 *
 * @param user - User ID to fetch data for
 * @param interval - Interval to aggregate data for
 * @param filter - Filter to apply (e.g. 'project:wakapi' or 'language:Go')
 */
export async function getBadge(
  config: ClientConfig,
  { user, interval, filter }: GetBadgeParams,
  requestOptions?: RequestOptions,
): Promise<V1BadgeData> {
  const _resp = await sdkRequest<V1BadgeData>({
    method: "GET",
    path: `/compat/shields/v1/${encodePathSegment(user)}/${encodePathSegment(interval)}/${encodePathSegment(filter)}`,
    operationId: "getBadge",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class BadgesNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Retrieves badge data for a user, interval, and filter in a format compatible with Shields.io. Use `interval` to choose the aggregation period and `filter` to select an entity such as a project or language; public data access must be enabled for the user.
   *
   * Retrieve total time for a given entity (e.g. a project) within a given range (e.g. one week) in a format compatible with [Shields.io](https://shields.io/endpoint). Requires public data access to be allowed.
   */
  get(params: GetBadgeParams, requestOptions?: RequestOptions): ReturnType<typeof getBadge> {
    return getBadge(this._config, params, requestOptions);
  }
}
