// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ModelsDiagnostics } from "../types/diagnostics";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

export type PostDiagnosticsParams = ModelsDiagnostics;

/**
 * Submits a diagnostics object sent by the WakaTime CLI. Include diagnostic details such as the CLI version, platform, logs, or stack trace to provide context for the reported issue.
 *
 * @param architecture - Optional `string` value serialized in the `architecture`
 *   wire field.
 * @param cliVersion - Optional `string` value serialized in the `cli_version`
 *   wire field.
 * @param id - Optional `integer` value serialized in the `id` wire field.
 * @param logs - Optional `string` value serialized in the `logs` wire field.
 * @param platform - Optional `string` value serialized in the `platform` wire
 *   field.
 * @param plugin - Optional `string` value serialized in the `plugin` wire field.
 * @param stacktrace - Optional `string` value serialized in the `stacktrace`
 *   wire field.
 */
export async function postDiagnostics(
  config: ClientConfig,
  { architecture, cliVersion, id, logs, platform, plugin, stacktrace }: PostDiagnosticsParams = {},
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/plugins/errors`,
    operationId: "postDiagnostics",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      architecture,
      cli_version: cliVersion,
      id,
      logs,
      platform,
      plugin,
      stacktrace,
    },
    config,
  });
  void _resp.data;
  return;
}

export class DiagnosticsNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Submits a diagnostics object sent by the WakaTime CLI. Include diagnostic details such as the CLI version, platform, logs, or stack trace to provide context for the reported issue.
   */
  post(
    params: PostDiagnosticsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof postDiagnostics> {
    return postDiagnostics(this._config, params, requestOptions);
  }
}
