// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ModelsHeartbeat, V1HeartbeatsResult } from "../types/heartbeat";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest, toWire } from "../client";

export interface GetHeartbeatsParams {
  user: string;
  date: string;
}

/**
 * Lists a user's heartbeats for a specified date. Provide `date` to select the day and `user` to identify whose activity to retrieve.
 *
 * @param user - Username (or current)
 * @param date - Date
 */
export async function getHeartbeats(
  config: ClientConfig,
  { user, date }: GetHeartbeatsParams,
  requestOptions?: RequestOptions,
): Promise<V1HeartbeatsResult> {
  const _resp = await sdkRequest<V1HeartbeatsResult>({
    method: "GET",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}/heartbeats`,
    operationId: "getHeartbeats",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      date: queryValue(date, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "V1HeartbeatsResult") as V1HeartbeatsResult;
}

export type PostHeartbeat3Params = ModelsHeartbeat & {
  user: string;
};

/**
 * Creates a single heartbeat for a user from a WakaTime-compatible request. Send the heartbeat as a JSON object; `created_at` is numeric, and the `editor` field is ignored.
 *
 * @param user - Username (or current)
 * @param aiInputTokens - Optional `integer` value serialized in the
 *   `ai_input_tokens` wire field.
 * @param aiLineChanges - Optional `integer` value serialized in the
 *   `ai_line_changes` wire field.
 * @param aiOutputTokens - Optional `integer` value serialized in the
 *   `ai_output_tokens` wire field.
 * @param aiPromptLength - Optional `integer` value serialized in the
 *   `ai_prompt_length` wire field.
 * @param aiSession - Optional `string` value serialized in the `ai_session` wire
 *   field.
 * @param branch - Optional `string` value serialized in the `branch` wire field.
 * @param category - Optional `string` value serialized in the `category` wire
 *   field.
 * @param createdAt - https://gorm.io/docs/conventions.html#CreatedAt
 * @param cursorpos - Optional `integer` value serialized in the `cursorpos` wire
 *   field.
 * @param editor - ignored because editor might be parsed differently by wakatime
 * @param entity - Optional `string` value serialized in the `entity` wire field.
 * @param humanLineChanges - Optional `integer` value serialized in the
 *   `human_line_changes` wire field.
 * @param isWrite - Optional `boolean` value serialized in the `is_write` wire
 *   field.
 * @param language - Optional `string` value serialized in the `language` wire
 *   field.
 * @param lineAdditions - Optional `integer` value serialized in the
 *   `line_additions` wire field.
 * @param lineDeletions - Optional `integer` value serialized in the
 *   `line_deletions` wire field.
 * @param lineno - Optional `integer` value serialized in the `lineno` wire
 *   field.
 * @param lines - Optional `integer` value serialized in the `lines` wire field.
 * @param machine - ignored because wakatime api doesn't return machines
 *   currently
 * @param operatingSystem - ignored because os might be parsed differently by
 *   wakatime
 * @param project - Optional `string` value serialized in the `project` wire
 *   field.
 * @param projectRootCount - Optional `integer` value serialized in the
 *   `project_root_count` wire field.
 * @param time - note: on sqlite, table will have an additional column
 *   `time_real`, introduced "manually" by migration 20260111 see
 *   https://github.com/muety/wakapi/issues/882 for details
 * @param type_ - Optional `string` value serialized in the `type` wire field.
 * @param userAgent - Optional `string` value serialized in the `user_agent` wire
 *   field.
 */
export async function postHeartbeat3(
  config: ClientConfig,
  {
    user,
    aiInputTokens,
    aiLineChanges,
    aiOutputTokens,
    aiPromptLength,
    aiSession,
    branch,
    category,
    createdAt,
    cursorpos,
    editor,
    entity,
    humanLineChanges,
    isWrite,
    language,
    lineAdditions,
    lineDeletions,
    lineno,
    lines,
    machine,
    operatingSystem,
    project,
    projectRootCount,
    time,
    type: type_,
    userAgent,
  }: PostHeartbeat3Params,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}/heartbeats`,
    operationId: "postHeartbeat3",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      ai_input_tokens: aiInputTokens,
      ai_line_changes: aiLineChanges,
      ai_output_tokens: aiOutputTokens,
      ai_prompt_length: aiPromptLength,
      ai_session: aiSession,
      branch,
      category,
      created_at: createdAt,
      cursorpos,
      editor,
      entity,
      human_line_changes: humanLineChanges,
      is_write: isWrite,
      language,
      line_additions: lineAdditions,
      line_deletions: lineDeletions,
      lineno,
      lines,
      machine,
      operating_system: operatingSystem,
      project,
      project_root_count: projectRootCount,
      time,
      ["type"]: type_,
      user_agent: userAgent,
    },
    config,
  });
  void _resp.data;
  return;
}

export interface PostHeartbeat7Params {
  user: string;
  body: ModelsHeartbeat[];
}

/**
 * Creates multiple heartbeats for a user from a WakaTime-compatible request. Send a JSON array of heartbeat objects; each object can include fields such as `entity`, `language`, and `created_at`.
 *
 * @param user - Username (or current)
 */
export async function postHeartbeat7(
  config: ClientConfig,
  { user, body }: PostHeartbeat7Params,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}/heartbeats.bulk`,
    operationId: "postHeartbeat7",
    responseDecoder: "empty",
    ...requestOptions,
    body: toWire(body, "ModelsHeartbeat"),
    config,
  });
  void _resp.data;
  return;
}

export type PostHeartbeatParams = ModelsHeartbeat;

/**
 * Submits a single heartbeat containing activity data. Send the heartbeat as a JSON object, using fields such as `entity`, `category`, and `language` to describe the recorded activity.
 *
 * @param aiInputTokens - Optional `integer` value serialized in the
 *   `ai_input_tokens` wire field.
 * @param aiLineChanges - Optional `integer` value serialized in the
 *   `ai_line_changes` wire field.
 * @param aiOutputTokens - Optional `integer` value serialized in the
 *   `ai_output_tokens` wire field.
 * @param aiPromptLength - Optional `integer` value serialized in the
 *   `ai_prompt_length` wire field.
 * @param aiSession - Optional `string` value serialized in the `ai_session` wire
 *   field.
 * @param branch - Optional `string` value serialized in the `branch` wire field.
 * @param category - Optional `string` value serialized in the `category` wire
 *   field.
 * @param createdAt - https://gorm.io/docs/conventions.html#CreatedAt
 * @param cursorpos - Optional `integer` value serialized in the `cursorpos` wire
 *   field.
 * @param editor - ignored because editor might be parsed differently by wakatime
 * @param entity - Optional `string` value serialized in the `entity` wire field.
 * @param humanLineChanges - Optional `integer` value serialized in the
 *   `human_line_changes` wire field.
 * @param isWrite - Optional `boolean` value serialized in the `is_write` wire
 *   field.
 * @param language - Optional `string` value serialized in the `language` wire
 *   field.
 * @param lineAdditions - Optional `integer` value serialized in the
 *   `line_additions` wire field.
 * @param lineDeletions - Optional `integer` value serialized in the
 *   `line_deletions` wire field.
 * @param lineno - Optional `integer` value serialized in the `lineno` wire
 *   field.
 * @param lines - Optional `integer` value serialized in the `lines` wire field.
 * @param machine - ignored because wakatime api doesn't return machines
 *   currently
 * @param operatingSystem - ignored because os might be parsed differently by
 *   wakatime
 * @param project - Optional `string` value serialized in the `project` wire
 *   field.
 * @param projectRootCount - Optional `integer` value serialized in the
 *   `project_root_count` wire field.
 * @param time - note: on sqlite, table will have an additional column
 *   `time_real`, introduced "manually" by migration 20260111 see
 *   https://github.com/muety/wakapi/issues/882 for details
 * @param type_ - Optional `string` value serialized in the `type` wire field.
 * @param userAgent - Optional `string` value serialized in the `user_agent` wire
 *   field.
 */
export async function postHeartbeat(
  config: ClientConfig,
  {
    aiInputTokens,
    aiLineChanges,
    aiOutputTokens,
    aiPromptLength,
    aiSession,
    branch,
    category,
    createdAt,
    cursorpos,
    editor,
    entity,
    humanLineChanges,
    isWrite,
    language,
    lineAdditions,
    lineDeletions,
    lineno,
    lines,
    machine,
    operatingSystem,
    project,
    projectRootCount,
    time,
    type: type_,
    userAgent,
  }: PostHeartbeatParams = {},
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/heartbeat`,
    operationId: "postHeartbeat",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      ai_input_tokens: aiInputTokens,
      ai_line_changes: aiLineChanges,
      ai_output_tokens: aiOutputTokens,
      ai_prompt_length: aiPromptLength,
      ai_session: aiSession,
      branch,
      category,
      created_at: createdAt,
      cursorpos,
      editor,
      entity,
      human_line_changes: humanLineChanges,
      is_write: isWrite,
      language,
      line_additions: lineAdditions,
      line_deletions: lineDeletions,
      lineno,
      lines,
      machine,
      operating_system: operatingSystem,
      project,
      project_root_count: projectRootCount,
      time,
      ["type"]: type_,
      user_agent: userAgent,
    },
    config,
  });
  void _resp.data;
  return;
}

/**
 * Submits multiple heartbeats in one request. Send a JSON array of heartbeat objects to record activity in bulk.
 */
export async function postHeartbeat5(
  config: ClientConfig,
  body: ModelsHeartbeat[],
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/heartbeats`,
    operationId: "postHeartbeat5",
    responseDecoder: "empty",
    ...requestOptions,
    body: toWire(body, "ModelsHeartbeat"),
    config,
  });
  void _resp.data;
  return;
}

export type PostHeartbeat4Params = ModelsHeartbeat & {
  user: string;
};

/**
 * Submits a single heartbeat for a specified user. Send the heartbeat as a JSON object containing activity data such as `entity`, `category`, and `language`.
 *
 * @param user - Username (or current)
 * @param aiInputTokens - Optional `integer` value serialized in the
 *   `ai_input_tokens` wire field.
 * @param aiLineChanges - Optional `integer` value serialized in the
 *   `ai_line_changes` wire field.
 * @param aiOutputTokens - Optional `integer` value serialized in the
 *   `ai_output_tokens` wire field.
 * @param aiPromptLength - Optional `integer` value serialized in the
 *   `ai_prompt_length` wire field.
 * @param aiSession - Optional `string` value serialized in the `ai_session` wire
 *   field.
 * @param branch - Optional `string` value serialized in the `branch` wire field.
 * @param category - Optional `string` value serialized in the `category` wire
 *   field.
 * @param createdAt - https://gorm.io/docs/conventions.html#CreatedAt
 * @param cursorpos - Optional `integer` value serialized in the `cursorpos` wire
 *   field.
 * @param editor - ignored because editor might be parsed differently by wakatime
 * @param entity - Optional `string` value serialized in the `entity` wire field.
 * @param humanLineChanges - Optional `integer` value serialized in the
 *   `human_line_changes` wire field.
 * @param isWrite - Optional `boolean` value serialized in the `is_write` wire
 *   field.
 * @param language - Optional `string` value serialized in the `language` wire
 *   field.
 * @param lineAdditions - Optional `integer` value serialized in the
 *   `line_additions` wire field.
 * @param lineDeletions - Optional `integer` value serialized in the
 *   `line_deletions` wire field.
 * @param lineno - Optional `integer` value serialized in the `lineno` wire
 *   field.
 * @param lines - Optional `integer` value serialized in the `lines` wire field.
 * @param machine - ignored because wakatime api doesn't return machines
 *   currently
 * @param operatingSystem - ignored because os might be parsed differently by
 *   wakatime
 * @param project - Optional `string` value serialized in the `project` wire
 *   field.
 * @param projectRootCount - Optional `integer` value serialized in the
 *   `project_root_count` wire field.
 * @param time - note: on sqlite, table will have an additional column
 *   `time_real`, introduced "manually" by migration 20260111 see
 *   https://github.com/muety/wakapi/issues/882 for details
 * @param type_ - Optional `string` value serialized in the `type` wire field.
 * @param userAgent - Optional `string` value serialized in the `user_agent` wire
 *   field.
 */
export async function postHeartbeat4(
  config: ClientConfig,
  {
    user,
    aiInputTokens,
    aiLineChanges,
    aiOutputTokens,
    aiPromptLength,
    aiSession,
    branch,
    category,
    createdAt,
    cursorpos,
    editor,
    entity,
    humanLineChanges,
    isWrite,
    language,
    lineAdditions,
    lineDeletions,
    lineno,
    lines,
    machine,
    operatingSystem,
    project,
    projectRootCount,
    time,
    type: type_,
    userAgent,
  }: PostHeartbeat4Params,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/users/${encodePathSegment(user)}/heartbeats`,
    operationId: "postHeartbeat4",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      ai_input_tokens: aiInputTokens,
      ai_line_changes: aiLineChanges,
      ai_output_tokens: aiOutputTokens,
      ai_prompt_length: aiPromptLength,
      ai_session: aiSession,
      branch,
      category,
      created_at: createdAt,
      cursorpos,
      editor,
      entity,
      human_line_changes: humanLineChanges,
      is_write: isWrite,
      language,
      line_additions: lineAdditions,
      line_deletions: lineDeletions,
      lineno,
      lines,
      machine,
      operating_system: operatingSystem,
      project,
      project_root_count: projectRootCount,
      time,
      ["type"]: type_,
      user_agent: userAgent,
    },
    config,
  });
  void _resp.data;
  return;
}

export interface PostHeartbeat8Params {
  user: string;
  body: ModelsHeartbeat[];
}

/**
 * Submits multiple heartbeats for a specified user in one request. Send a JSON array of heartbeat objects to record activity in bulk.
 *
 * @param user - Username (or current)
 */
export async function postHeartbeat8(
  config: ClientConfig,
  { user, body }: PostHeartbeat8Params,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/users/${encodePathSegment(user)}/heartbeats.bulk`,
    operationId: "postHeartbeat8",
    responseDecoder: "empty",
    ...requestOptions,
    body: toWire(body, "ModelsHeartbeat"),
    config,
  });
  void _resp.data;
  return;
}

export type PostHeartbeat2Params = ModelsHeartbeat & {
  user: string;
};

/**
 * Creates a heartbeat for the specified user. Submit a JSON object with the activity data you want to record, such as `entity`, `language`, `category`, and line-change values. The schema does not mark any heartbeat fields as required.
 *
 * @param user - Username (or current)
 * @param aiInputTokens - Optional `integer` value serialized in the
 *   `ai_input_tokens` wire field.
 * @param aiLineChanges - Optional `integer` value serialized in the
 *   `ai_line_changes` wire field.
 * @param aiOutputTokens - Optional `integer` value serialized in the
 *   `ai_output_tokens` wire field.
 * @param aiPromptLength - Optional `integer` value serialized in the
 *   `ai_prompt_length` wire field.
 * @param aiSession - Optional `string` value serialized in the `ai_session` wire
 *   field.
 * @param branch - Optional `string` value serialized in the `branch` wire field.
 * @param category - Optional `string` value serialized in the `category` wire
 *   field.
 * @param createdAt - https://gorm.io/docs/conventions.html#CreatedAt
 * @param cursorpos - Optional `integer` value serialized in the `cursorpos` wire
 *   field.
 * @param editor - ignored because editor might be parsed differently by wakatime
 * @param entity - Optional `string` value serialized in the `entity` wire field.
 * @param humanLineChanges - Optional `integer` value serialized in the
 *   `human_line_changes` wire field.
 * @param isWrite - Optional `boolean` value serialized in the `is_write` wire
 *   field.
 * @param language - Optional `string` value serialized in the `language` wire
 *   field.
 * @param lineAdditions - Optional `integer` value serialized in the
 *   `line_additions` wire field.
 * @param lineDeletions - Optional `integer` value serialized in the
 *   `line_deletions` wire field.
 * @param lineno - Optional `integer` value serialized in the `lineno` wire
 *   field.
 * @param lines - Optional `integer` value serialized in the `lines` wire field.
 * @param machine - ignored because wakatime api doesn't return machines
 *   currently
 * @param operatingSystem - ignored because os might be parsed differently by
 *   wakatime
 * @param project - Optional `string` value serialized in the `project` wire
 *   field.
 * @param projectRootCount - Optional `integer` value serialized in the
 *   `project_root_count` wire field.
 * @param time - note: on sqlite, table will have an additional column
 *   `time_real`, introduced "manually" by migration 20260111 see
 *   https://github.com/muety/wakapi/issues/882 for details
 * @param type_ - Optional `string` value serialized in the `type` wire field.
 * @param userAgent - Optional `string` value serialized in the `user_agent` wire
 *   field.
 */
export async function postHeartbeat2(
  config: ClientConfig,
  {
    user,
    aiInputTokens,
    aiLineChanges,
    aiOutputTokens,
    aiPromptLength,
    aiSession,
    branch,
    category,
    createdAt,
    cursorpos,
    editor,
    entity,
    humanLineChanges,
    isWrite,
    language,
    lineAdditions,
    lineDeletions,
    lineno,
    lines,
    machine,
    operatingSystem,
    project,
    projectRootCount,
    time,
    type: type_,
    userAgent,
  }: PostHeartbeat2Params,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/v1/users/${encodePathSegment(user)}/heartbeats`,
    operationId: "postHeartbeat2",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      ai_input_tokens: aiInputTokens,
      ai_line_changes: aiLineChanges,
      ai_output_tokens: aiOutputTokens,
      ai_prompt_length: aiPromptLength,
      ai_session: aiSession,
      branch,
      category,
      created_at: createdAt,
      cursorpos,
      editor,
      entity,
      human_line_changes: humanLineChanges,
      is_write: isWrite,
      language,
      line_additions: lineAdditions,
      line_deletions: lineDeletions,
      lineno,
      lines,
      machine,
      operating_system: operatingSystem,
      project,
      project_root_count: projectRootCount,
      time,
      ["type"]: type_,
      user_agent: userAgent,
    },
    config,
  });
  void _resp.data;
  return;
}

export interface PostHeartbeat6Params {
  user: string;
  body: ModelsHeartbeat[];
}

/**
 * Creates multiple heartbeats for the specified user. Submit a JSON array of heartbeat objects containing the activity data you want to record. The schema does not mark any fields within the heartbeat objects as required.
 *
 * @param user - Username (or current)
 */
export async function postHeartbeat6(
  config: ClientConfig,
  { user, body }: PostHeartbeat6Params,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/v1/users/${encodePathSegment(user)}/heartbeats.bulk`,
    operationId: "postHeartbeat6",
    responseDecoder: "empty",
    ...requestOptions,
    body: toWire(body, "ModelsHeartbeat"),
    config,
  });
  void _resp.data;
  return;
}

export class HeartbeatNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists a user's heartbeats for a specified date. Provide `date` to select the day and `user` to identify whose activity to retrieve.
   */
  get(
    params: GetHeartbeatsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getHeartbeats> {
    return getHeartbeats(this._config, params, requestOptions);
  }
  /**
   * Creates a single heartbeat for a user from a WakaTime-compatible request. Send the heartbeat as a JSON object; `created_at` is numeric, and the `editor` field is ignored.
   */
  post3(
    params: PostHeartbeat3Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof postHeartbeat3> {
    return postHeartbeat3(this._config, params, requestOptions);
  }
  /**
   * Creates multiple heartbeats for a user from a WakaTime-compatible request. Send a JSON array of heartbeat objects; each object can include fields such as `entity`, `language`, and `created_at`.
   */
  post7(
    params: PostHeartbeat7Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof postHeartbeat7> {
    return postHeartbeat7(this._config, params, requestOptions);
  }
  /**
   * Submits a single heartbeat containing activity data. Send the heartbeat as a JSON object, using fields such as `entity`, `category`, and `language` to describe the recorded activity.
   */
  post(
    params: PostHeartbeatParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof postHeartbeat> {
    return postHeartbeat(this._config, params, requestOptions);
  }
  /**
   * Submits multiple heartbeats in one request. Send a JSON array of heartbeat objects to record activity in bulk.
   */
  post5(
    body: ModelsHeartbeat[],
    requestOptions?: RequestOptions,
  ): ReturnType<typeof postHeartbeat5> {
    return postHeartbeat5(this._config, body, requestOptions);
  }
  /**
   * Submits a single heartbeat for a specified user. Send the heartbeat as a JSON object containing activity data such as `entity`, `category`, and `language`.
   */
  post4(
    params: PostHeartbeat4Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof postHeartbeat4> {
    return postHeartbeat4(this._config, params, requestOptions);
  }
  /**
   * Submits multiple heartbeats for a specified user in one request. Send a JSON array of heartbeat objects to record activity in bulk.
   */
  post8(
    params: PostHeartbeat8Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof postHeartbeat8> {
    return postHeartbeat8(this._config, params, requestOptions);
  }
  /**
   * Creates a heartbeat for the specified user. Submit a JSON object with the activity data you want to record, such as `entity`, `language`, `category`, and line-change values. The schema does not mark any heartbeat fields as required.
   */
  post2(
    params: PostHeartbeat2Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof postHeartbeat2> {
    return postHeartbeat2(this._config, params, requestOptions);
  }
  /**
   * Creates multiple heartbeats for the specified user. Submit a JSON array of heartbeat objects containing the activity data you want to record. The schema does not mark any fields within the heartbeat objects as required.
   */
  post6(
    params: PostHeartbeat6Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof postHeartbeat6> {
    return postHeartbeat6(this._config, params, requestOptions);
  }
}
