// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

/**
 * Retrieves the application's health status. Use this endpoint to check the service's current health without supplying request parameters or a body.
 */
export async function getHealth(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "GET",
    path: `/health`,
    operationId: "getHealth",
    responseDecoder: "text",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class MiscNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Retrieves the application's health status. Use this endpoint to check the service's current health without supplying request parameters or a body.
   */
  getHealth(requestOptions?: RequestOptions): ReturnType<typeof getHealth> {
    return getHealth(this._config, requestOptions);
  }
}
