// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ModelsSummary } from "../types/summary";
import type { ClientConfig, RequestOptions } from "../client";
import { fromWire, queryValue, sdkRequest } from "../client";

export interface GetSummaryParams {
  interval?:
    | "today"
    | "yesterday"
    | "week"
    | "month"
    | "year"
    | "7_days"
    | "last_7_days"
    | "30_days"
    | "last_30_days"
    | "6_months"
    | "last_6_months"
    | "12_months"
    | "last_12_months"
    | "last_year"
    | "any"
    | "all_time"
    | (string & {});
  from?: string;
  to?: string;
  recompute?: boolean;
  project?: string;
  language?: string;
  editor?: string;
  operatingSystem?: string;
  machine?: string;
  label?: string;
}

/**
 * Retrieves a summary of activity for the requested interval or date range. Use `from` and `to` to define the period, and apply project, language, editor, operating system, machine, or label filters to narrow the summary.
 *
 * @param interval - Interval identifier
 * @param from - Start date (e.g. '2021-02-07')
 * @param to - End date (e.g. '2021-02-08')
 * @param recompute - Whether to recompute the summary from raw heartbeat or use
 *   cache
 * @param project - Project to filter by
 * @param language - Language to filter by
 * @param editor - Editor to filter by
 * @param operatingSystem - OS to filter by
 * @param machine - Machine to filter by
 * @param label - Project label to filter by
 */
export async function getSummary(
  config: ClientConfig,
  {
    interval,
    from,
    to,
    recompute,
    project,
    language,
    editor,
    operatingSystem,
    machine,
    label,
  }: GetSummaryParams = {},
  requestOptions?: RequestOptions,
): Promise<ModelsSummary> {
  const _resp = await sdkRequest<ModelsSummary>({
    method: "GET",
    path: `/summary`,
    operationId: "getSummary",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      interval: queryValue(interval, "form", true),
      from: queryValue(from, "form", true),
      to: queryValue(to, "form", true),
      recompute: queryValue(recompute, "form", true),
      project: queryValue(project, "form", true),
      language: queryValue(language, "form", true),
      editor: queryValue(editor, "form", true),
      operating_system: queryValue(operatingSystem, "form", true),
      machine: queryValue(machine, "form", true),
      label: queryValue(label, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ModelsSummary") as ModelsSummary;
}

export class SummaryNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Retrieves a summary of activity for the requested interval or date range. Use `from` and `to` to define the period, and apply project, language, editor, operating system, machine, or label filters to narrow the summary.
   */
  get(
    params: GetSummaryParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getSummary> {
    return getSummary(this._config, params, requestOptions);
  }
}
