// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  V1AllTimeViewModel,
  V1LeadersViewModel,
  V1ProjectViewModel,
  V1ProjectsViewModel,
  V1StatsViewModel,
  V1StatusBarViewModel,
  V1SummariesViewModel,
  V1UserAgentsViewModel,
  V1UserViewModel,
} from "../types/wakatime";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest } from "../client";

/**
 * Lists users ranked by coding activity in descending order. Use this endpoint to retrieve the leaderboard, including its ranking data, current-user information, and range metadata.
 *
 * Mimics https://wakatime.com/developers#leaders
 */
export async function getWakatimeLeaders(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<V1LeadersViewModel> {
  const _resp = await sdkRequest<V1LeadersViewModel>({
    method: "GET",
    path: `/compat/wakatime/v1/leaders`,
    operationId: "getWakatimeLeaders",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "V1LeadersViewModel") as V1LeadersViewModel;
}

export interface GetWakatimeUserParams {
  user: string;
}

/**
 * Retrieves a user's profile information. Set `user` to a user ID or `current` to retrieve the profile associated with the authenticated user.
 *
 * Mimics https://wakatime.com/developers#users
 *
 * @param user - User ID to fetch (or 'current')
 */
export async function getWakatimeUser(
  config: ClientConfig,
  { user }: GetWakatimeUserParams,
  requestOptions?: RequestOptions,
): Promise<V1UserViewModel> {
  const _resp = await sdkRequest<V1UserViewModel>({
    method: "GET",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}`,
    operationId: "getWakatimeUser",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "V1UserViewModel") as V1UserViewModel;
}

export interface GetAllTimeParams {
  user: string;
}

/**
 * Retrieves a user's coding-time summary for all time since today. Set `user` to a user ID or `current` to select the user whose summary you want.
 *
 * Mimics https://wakatime.com/developers#all_time_since_today
 *
 * @param user - User ID to fetch data for (or 'current')
 */
export async function getAllTime(
  config: ClientConfig,
  { user }: GetAllTimeParams,
  requestOptions?: RequestOptions,
): Promise<V1AllTimeViewModel> {
  const _resp = await sdkRequest<V1AllTimeViewModel>({
    method: "GET",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}/all_time_since_today`,
    operationId: "getAllTime",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "V1AllTimeViewModel") as V1AllTimeViewModel;
}

export interface GetWakatimeProjectsParams {
  user: string;
  q?: string;
}

/**
 * Lists a user's projects. Set `user` to a user ID or `current`, and optionally use `q` to filter the projects.
 *
 * Mimics https://wakatime.com/developers#projects
 *
 * @param user - User ID to fetch data for (or 'current')
 * @param q - Query to filter projects by
 */
export async function getWakatimeProjects(
  config: ClientConfig,
  { user, q }: GetWakatimeProjectsParams,
  requestOptions?: RequestOptions,
): Promise<V1ProjectsViewModel> {
  const _resp = await sdkRequest<V1ProjectsViewModel>({
    method: "GET",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}/projects`,
    operationId: "getWakatimeProjects",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      q: queryValue(q, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "V1ProjectsViewModel") as V1ProjectsViewModel;
}

export interface GetWakatimeProjectParams {
  user: string;
  id: string;
}

/**
 * Retrieves a single project for a specified user. Provide `user` to select the user and `id` to identify the project.
 *
 * Mimics undocumented endpoint related to https://wakatime.com/developers#projects
 *
 * @param user - User ID to fetch data for (or 'current')
 * @param id - Project ID to fetch
 */
export async function getWakatimeProject(
  config: ClientConfig,
  { user, id }: GetWakatimeProjectParams,
  requestOptions?: RequestOptions,
): Promise<V1ProjectViewModel> {
  const _resp = await sdkRequest<V1ProjectViewModel>({
    method: "GET",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}/projects/${encodePathSegment(id)}`,
    operationId: "getWakatimeProject",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "V1ProjectViewModel") as V1ProjectViewModel;
}

export interface GetWakatimesTatsParams {
  user: string;
  range?:
    | "today"
    | "yesterday"
    | "week"
    | "month"
    | "year"
    | "7_days"
    | "last_7_days"
    | "30_days"
    | "last_30_days"
    | "6_months"
    | "last_6_months"
    | "12_months"
    | "last_12_months"
    | "last_year"
    | "any"
    | "all_time"
    | (string & {});
  project?: string;
  language?: string;
  editor?: string;
  operatingSystem?: string;
  machine?: string;
  label?: string;
}

/**
 * Retrieves coding-activity statistics for a user over a selected interval. Use the optional query parameters to filter the statistics by project, language, editor, operating system, machine, or project label.
 *
 * Mimics https://wakatime.com/developers#stats
 *
 * @param user - User ID to fetch data for (or 'current')
 * @param range - Range interval identifier
 * @param project - Project to filter by
 * @param language - Language to filter by
 * @param editor - Editor to filter by
 * @param operatingSystem - OS to filter by
 * @param machine - Machine to filter by
 * @param label - Project label to filter by
 */
export async function getWakatimesTats(
  config: ClientConfig,
  {
    user,
    range,
    project,
    language,
    editor,
    operatingSystem,
    machine,
    label,
  }: GetWakatimesTatsParams,
  requestOptions?: RequestOptions,
): Promise<V1StatsViewModel> {
  const _resp = await sdkRequest<V1StatsViewModel>({
    method: "GET",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}/stats/${encodePathSegment(range)}`,
    operationId: "getWakatimesTats",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      project: queryValue(project, "form", true),
      language: queryValue(language, "form", true),
      editor: queryValue(editor, "form", true),
      operating_system: queryValue(operatingSystem, "form", true),
      machine: queryValue(machine, "form", true),
      label: queryValue(label, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "V1StatsViewModel") as V1StatsViewModel;
}

export interface GetWakatimeSummariesParams {
  user: string;
  range?:
    | "today"
    | "yesterday"
    | "week"
    | "month"
    | "year"
    | "7_days"
    | "last_7_days"
    | "30_days"
    | "last_30_days"
    | "6_months"
    | "last_6_months"
    | "12_months"
    | "last_12_months"
    | "last_year"
    | "any"
    | "all_time"
    | (string & {});
  start?: string;
  end?: string;
  project?: string;
  language?: string;
  editor?: string;
  operatingSystem?: string;
  machine?: string;
  label?: string;
}

/**
 * Retrieves WakaTime-compatible summaries for a specified user. Use `range` or the `start` and `end` dates to select a period, and apply project, language, editor, operating system, machine, or label filters to narrow the results.
 *
 * Mimics https://wakatime.com/developers#summaries.
 *
 * @param user - User ID to fetch data for (or 'current')
 * @param range - Range interval identifier
 * @param start - Start date (e.g. '2021-02-07')
 * @param end - End date (e.g. '2021-02-08')
 * @param project - Project to filter by
 * @param language - Language to filter by
 * @param editor - Editor to filter by
 * @param operatingSystem - OS to filter by
 * @param machine - Machine to filter by
 * @param label - Project label to filter by
 */
export async function getWakatimeSummaries(
  config: ClientConfig,
  {
    user,
    range,
    start,
    end,
    project,
    language,
    editor,
    operatingSystem,
    machine,
    label,
  }: GetWakatimeSummariesParams,
  requestOptions?: RequestOptions,
): Promise<V1SummariesViewModel> {
  const _resp = await sdkRequest<V1SummariesViewModel>({
    method: "GET",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}/summaries`,
    operationId: "getWakatimeSummaries",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      range: queryValue(range, "form", true),
      start: queryValue(start, "form", true),
      end: queryValue(end, "form", true),
      project: queryValue(project, "form", true),
      language: queryValue(language, "form", true),
      editor: queryValue(editor, "form", true),
      operating_system: queryValue(operatingSystem, "form", true),
      machine: queryValue(machine, "form", true),
      label: queryValue(label, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "V1SummariesViewModel") as V1SummariesViewModel;
}

export interface GetWakatimeUseragentsParams {
  user: string;
}

/**
 * Lists the unique user agents recorded for a specified user. Use the `user` path parameter to select the user whose agent history you want to inspect.
 *
 * Mimics https://wakatime.com/developers#user_agents
 *
 * @param user - User ID to fetch data for (or 'current')
 */
export async function getWakatimeUseragents(
  config: ClientConfig,
  { user }: GetWakatimeUseragentsParams,
  requestOptions?: RequestOptions,
): Promise<V1UserAgentsViewModel> {
  const _resp = await sdkRequest<V1UserAgentsViewModel>({
    method: "GET",
    path: `/compat/wakatime/v1/users/${encodePathSegment(user)}/user_agents`,
    operationId: "getWakatimeUseragents",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "V1UserAgentsViewModel") as V1UserAgentsViewModel;
}

export interface StatusbarParams {
  user: string;
}

/**
 * Retrieves today's activity summary for a specified user in a status-bar-compatible format. Use the `user` path parameter to select the user whose current-day activity you want to view.
 *
 * Mimics https://wakatime.com/api/v1/users/current/statusbar/today. Have no official documentation
 *
 * @param user - User ID to fetch data for (or 'current')
 */
export async function statusbar(
  config: ClientConfig,
  { user }: StatusbarParams,
  requestOptions?: RequestOptions,
): Promise<V1StatusBarViewModel> {
  const _resp = await sdkRequest<V1StatusBarViewModel>({
    method: "GET",
    path: `/users/${encodePathSegment(user)}/statusbar/today`,
    operationId: "statusbar",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "V1StatusBarViewModel") as V1StatusBarViewModel;
}

export class WakatimeNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists users ranked by coding activity in descending order. Use this endpoint to retrieve the leaderboard, including its ranking data, current-user information, and range metadata.
   *
   * Mimics https://wakatime.com/developers#leaders
   */
  getLeaders(requestOptions?: RequestOptions): ReturnType<typeof getWakatimeLeaders> {
    return getWakatimeLeaders(this._config, requestOptions);
  }
  /**
   * Retrieves a user's profile information. Set `user` to a user ID or `current` to retrieve the profile associated with the authenticated user.
   *
   * Mimics https://wakatime.com/developers#users
   */
  getUser(
    params: GetWakatimeUserParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getWakatimeUser> {
    return getWakatimeUser(this._config, params, requestOptions);
  }
  /**
   * Retrieves a user's coding-time summary for all time since today. Set `user` to a user ID or `current` to select the user whose summary you want.
   *
   * Mimics https://wakatime.com/developers#all_time_since_today
   */
  getAllTime(
    params: GetAllTimeParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getAllTime> {
    return getAllTime(this._config, params, requestOptions);
  }
  /**
   * Lists a user's projects. Set `user` to a user ID or `current`, and optionally use `q` to filter the projects.
   *
   * Mimics https://wakatime.com/developers#projects
   */
  getProjects(
    params: GetWakatimeProjectsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getWakatimeProjects> {
    return getWakatimeProjects(this._config, params, requestOptions);
  }
  /**
   * Retrieves a single project for a specified user. Provide `user` to select the user and `id` to identify the project.
   *
   * Mimics undocumented endpoint related to https://wakatime.com/developers#projects
   */
  getProject(
    params: GetWakatimeProjectParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getWakatimeProject> {
    return getWakatimeProject(this._config, params, requestOptions);
  }
  /**
   * Retrieves coding-activity statistics for a user over a selected interval. Use the optional query parameters to filter the statistics by project, language, editor, operating system, machine, or project label.
   *
   * Mimics https://wakatime.com/developers#stats
   */
  getTats(
    params: GetWakatimesTatsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getWakatimesTats> {
    return getWakatimesTats(this._config, params, requestOptions);
  }
  /**
   * Retrieves WakaTime-compatible summaries for a specified user. Use `range` or the `start` and `end` dates to select a period, and apply project, language, editor, operating system, machine, or label filters to narrow the results.
   *
   * Mimics https://wakatime.com/developers#summaries.
   */
  getSummaries(
    params: GetWakatimeSummariesParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getWakatimeSummaries> {
    return getWakatimeSummaries(this._config, params, requestOptions);
  }
  /**
   * Lists the unique user agents recorded for a specified user. Use the `user` path parameter to select the user whose agent history you want to inspect.
   *
   * Mimics https://wakatime.com/developers#user_agents
   */
  getUseragents(
    params: GetWakatimeUseragentsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getWakatimeUseragents> {
    return getWakatimeUseragents(this._config, params, requestOptions);
  }
  /**
   * Retrieves today's activity summary for a specified user in a status-bar-compatible format. Use the `user` path parameter to select the user whose current-day activity you want to view.
   *
   * Mimics https://wakatime.com/api/v1/users/current/statusbar/today. Have no official documentation
   */
  statusbar(
    params: StatusbarParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof statusbar> {
    return statusbar(this._config, params, requestOptions);
  }
}
