// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { encodePathSegment, queryValue, sdkRequest } from "../dist/index.js";
import { installFakeTransport } from "./fake-transport.mjs";

const fixture = JSON.parse(
  readFileSync(new URL("./sdk-behavior-cases.json", import.meta.url), "utf8"),
);

const config = {
  baseUrl: fixture.baseUrl,
  // Typed auth fields are spec-dependent (a bearer-only SDK has no apiKey
  // field); `auth.headers` exists in every language and is merged into every
  // request, so the suite configures the fixture's auth header union.
  auth: { headers: { ...fixture.authHeaders } },
  // A behavior case asserts one attempt, so a retryable status must not be
  // retried, and no idempotency key may be injected into the compared headers.
  retry: { maxAttempts: 1 },
  idempotency: { enabled: false, methods: [] },
};

/** Lower-cases header names so expectations are case-insensitive. */
const lower = (headers) =>
  Object.fromEntries(
    Object.entries(headers ?? {}).map(([name, value]) => [
      String(name).toLowerCase(),
      String(value),
    ]),
  );

/** The path a generated method builds: one encoded segment per path parameter. */
const buildPath = (item) => {
  let path = item.request.pathTemplate;
  for (const [name, value] of Object.entries(item.request.pathParameters)) {
    path = path.replaceAll("{" + name + "}", encodePathSegment(value));
  }
  return path;
};

const decodedBody = (item, data) => {
  if (item.response.kind === "bytes") {
    // The fetch engine decodes a binary body to a Blob, the axios engine to a
    // Uint8Array. Both are byte containers; measure whichever arrived rather
    // than reporting zero for the one this helper did not anticipate.
    if (data instanceof Uint8Array) return data.byteLength;
    if (data instanceof ArrayBuffer) return data.byteLength;
    if (typeof Blob !== "undefined" && data instanceof Blob) return data.size;
    return 0;
  }
  return data;
};

test("replays every generated behavior case through the request layer", async (t) => {
  for (const item of fixture.cases) {
    await t.test(item.id + " " + item.operationId, async () => {
      // Decode-only case: an authored response example carries contract
      // information, so only the decoding side is asserted.
      const requestSpec = item.request;
      const query = {};
      if (requestSpec) {
        for (const parameter of requestSpec.query) {
          const serialized = queryValue(parameter.value, parameter.style, parameter.explode);
          if (parameter.serialized !== null) {
            assert.deepEqual(
              serialized,
              parameter.serialized,
              "query serialization for " + parameter.name,
            );
          }
          if (serialized !== undefined) query[parameter.name] = serialized;
        }
      }

      const transport = installFakeTransport(() => {
        const headers = {};
        if (item.response.mediaType) headers["content-type"] = item.response.mediaType;
        return { status: item.response.status, headers, body: item.response.body };
      });
      const seen = transport.seen;
      // A 4xx/5xx case must REJECT with the SDK's typed error carrying the
      // decoded body — that is the typed-error contract, not a return value.
      const expectsError = item.response.status >= 400;
      try {
        const call = sdkRequest({
          method: requestSpec ? requestSpec.method : "GET",
          path: requestSpec ? buildPath(item) : "/behavior/" + item.id,
          operationId: item.operationId,
          query,
          ...(requestSpec && requestSpec.bodyKind !== null
            ? { body: requestSpec.body, contentType: requestSpec.contentType }
            : {}),
          ...(requestSpec && Object.keys(requestSpec.headers).length > 0
            ? { headers: requestSpec.headers }
            : {}),
          responseDecoder: item.response.kind,
          config,
        });
        let response = null;
        if (expectsError) {
          const error = await call.then(
            () => null,
            (thrown) => thrown,
          );
          assert.ok(error, "expected a typed error for status " + item.response.status);
          assert.equal(error.statusCode, item.response.status, "typed error status");
          assert.equal(
            error.name,
            item.response.errorKind ? "Sdk" + item.response.errorKind + "Error" : "SdkHttpError",
            "typed error class",
          );
          if (item.response.value !== undefined) {
            assert.deepEqual(error.body, item.response.value, "typed error body");
          }
        } else {
          response = await call;
        }
        if (requestSpec) {
          assert.equal(seen.method, item.expect.method, "method");
          // Space is "+" in form encoding and "%20" under RFC 3986; both are
          // accepted, so normalize before comparing. (NOTE: this suite source
          // lives in a JS template literal — no backticks inside it.)
          assert.equal(
            seen.url.replaceAll("%20", "+"),
            item.expect.url.replaceAll("%20", "+"),
            "request url",
          );
          const sent = lower(seen.headers);
          for (const [name, value] of Object.entries(item.expect.headers)) {
            // Only the multipart encoder knows the boundary, so the SDK leaves
            // Content-Type to the runtime for those requests; it is absent here
            // because the fake transport never reaches the runtime.
            if (
              name === "content-type" &&
              String(value).startsWith("multipart/form-data") &&
              sent[name] === undefined
            )
              continue;
            assert.equal(sent[name], value, "header " + name);
          }
          if (item.expect.bodyText !== null) {
            assert.equal(String(seen.body ?? ""), item.expect.bodyText, "request body");
          }
          if (item.expect.multipartFields !== null) {
            assert.ok(
              String(sent["content-type"] ?? item.expect.headers["content-type"]).startsWith(
                "multipart/form-data",
              ),
              "multipart content type",
            );
          }
        }
        if (expectsError) return;
        assert.equal(response.statusCode, item.response.status, "status");
        if (item.response.value !== undefined) {
          assert.deepEqual(
            decodedBody(item, response.data),
            item.response.value,
            "decoded response",
          );
        }
      } finally {
        transport.restore();
      }
    });
  }
});
