#!/usr/bin/env node

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

// AUTO-GENERATED. Schema-faithful SDK mock server; Node.js 20+.
import { readFileSync } from "node:fs";
import { createServer } from "node:http";

const portIndex = process.argv.indexOf("--port");
const PORT = portIndex >= 0 ? Number(process.argv[portIndex + 1]) : Number(process.env.PORT || 0);

const ROUTES = JSON.parse(readFileSync(new URL("./mock-routes.json", import.meta.url), "utf8"));
const META = JSON.parse(readFileSync(new URL("./mock-meta.json", import.meta.url), "utf8"));
const compiled = ROUTES.map((route) => ({
  ...route,
  regex: new RegExp(route.regexSource),
}));

function decodeRoutingPath(pathname) {
  try {
    return decodeURIComponent(String(pathname).replace(/%2F/gi, "%252F"));
  } catch {
    return String(pathname);
  }
}

// Stream frames and stream selectors both address a field by path, and the
// path may be nested ("data.entries"). One pair of helpers serves both.
function readAtPath(source, path) {
  let current = source;
  for (const segment of path) {
    if (current === null || typeof current !== "object") return undefined;
    current = current[segment];
  }
  return current;
}

// A create endpoint echoing back what it was sent is realistic for a scalar
// ("model", "name"). It is not for a structured field: request and response
// schemas that merely share a name — ChatCompletion's moderation is a request
// param on the way in and a results object on the way out — have different
// shapes, and echoing one into the other emits a body the response schema
// cannot describe.
function echoable(existing, incoming) {
  const scalar = (value) => value === null || typeof value !== "object";
  if (!scalar(existing) || !scalar(incoming)) return false;
  // Same JSON type, too. VideoResource.seconds is a string on the way out and
  // a number on the way in; echoing across that emits a body the response
  // schema does not describe.
  return typeof existing === typeof incoming;
}

function wrapAtPath(value, path) {
  let wrapped = value;
  for (let index = path.length - 1; index >= 0; index -= 1) {
    wrapped = { [path[index]]: wrapped };
  }
  return wrapped;
}

function writeHeaders(res, status, contentType, length) {
  const headers = {
    "Content-Type": contentType,
    "X-Mock-Server": META.title,
    "X-Request-ID": "req_mock_123",
  };
  if (length !== null) headers["Content-Length"] = length;
  res.writeHead(status, headers);
}

function sendMode(res, mode, requestedStatus) {
  const status = requestedStatus || Number(mode.statusCode) || 200;
  if (mode.decoderKind === "empty" || status === 204) {
    writeHeaders(
      res,
      status === 204 ? 204 : status,
      mode.mediaType || "application/octet-stream",
      0,
    );
    res.end();
    return;
  }
  if (mode.decoderKind === "sse") {
    writeHeaders(res, status, "text/event-stream; charset=utf-8", null);
    // When the operation declares where a frame carries its payload, the
    // example goes under that path so the frame matches what the SDK decodes.
    // Without it the frame is the example itself.
    const path = mode.streamEventField || [];
    const frame = path.length > 0 ? wrapAtPath(mode.example, path) : mode.example;
    res.write("data: " + JSON.stringify(frame) + "\n\n");
    res.end("data: [DONE]\n\n");
    return;
  }
  if (mode.decoderKind === "bytes") {
    const payload = Buffer.from(mode.bodyBase64 || "", "base64");
    writeHeaders(res, status, mode.mediaType || "application/octet-stream", payload.length);
    res.end(payload);
    return;
  }
  const payload =
    mode.decoderKind === "json"
      ? JSON.stringify(mode.example)
      : mode.decoderKind === "ndjson"
        ? jsonRecord(mode.mediaType, mode.example)
        : String(mode.example === null || mode.example === undefined ? "" : mode.example);
  const contentType =
    mode.mediaType || (mode.decoderKind === "json" ? "application/json" : "text/plain");
  writeHeaders(res, status, contentType, Buffer.byteLength(payload));
  res.end(payload);
}

function readRawBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

function parseMultipartFields(raw, contentType) {
  const boundary = /boundary=(?:"([^"]+)"|([^;]+))/i.exec(contentType);
  if (!boundary) return {};
  const marker = "--" + (boundary[1] || boundary[2]);
  const result = {};
  for (const part of raw.toString("latin1").split(marker)) {
    const name = /\r?\nContent-Disposition:[^\r\n]*\bname="([^"]+)"/i.exec(part)?.[1];
    if (!name) continue;
    const split = part.search(/\r?\n\r?\n/);
    // Splitting on the boundary marker leaves each part's terminating CRLF
    // attached, so a field echoed back would read "assistants\r\n".
    const value =
      split < 0
        ? ""
        : part
            .slice(split)
            .replace(/^\r?\n\r?\n/, "")
            .replace(/\r?\n--?$/, "")
            .replace(/\r?\n$/, "");
    // Several runtimes JSON-encode a string field into its part, so
    // "1024x1024" arrives wrapped in quotes. Unwrap that, but leave every
    // other part as text: a multipart body carries no types, and turning "4"
    // into a number here would disagree with every other reader of this body.
    let decoded = value;
    if (value.startsWith('"')) {
      try {
        const parsed = JSON.parse(value);
        if (typeof parsed === "string") decoded = parsed;
      } catch {
        // Not JSON — keep the raw text.
      }
    }
    if (name in result)
      result[name] = Array.isArray(result[name])
        ? [...result[name], decoded]
        : [result[name], decoded];
    else result[name] = decoded;
  }
  return result;
}

// One JSON record per line; a JSON text sequence also starts each with RS.
function jsonRecord(mediaType, value) {
  return (
    (/^application\/json-seq/i.test(mediaType || "") ? "\x1e" : "") + JSON.stringify(value) + "\n"
  );
}

function parseBody(raw, contentType, requestMode) {
  if (raw.length === 0) return null;
  const normalized = contentType.toLowerCase();
  if (
    requestMode?.encoderKind === "ndjson" &&
    normalized.startsWith(requestMode.mediaType.toLowerCase())
  ) {
    const text = raw.toString("utf8");
    try {
      return text
        .split("\n")
        .map((line) => line.replace("\x1e", "").trim())
        .filter((line) => line !== "")
        .map((line) => JSON.parse(line));
    } catch {
      return { __unparseable: text };
    }
  }
  if (normalized.includes("json")) {
    try {
      return JSON.parse(raw.toString("utf8"));
    } catch {
      return { __unparseable: raw.toString("utf8") };
    }
  }
  if (normalized.startsWith("multipart/form-data")) return parseMultipartFields(raw, contentType);
  if (normalized.startsWith("application/x-www-form-urlencoded")) {
    return Object.fromEntries(new URLSearchParams(raw.toString("utf8")));
  }
  return raw;
}

function selectRequestMode(route, contentType) {
  const normalized = contentType.toLowerCase();
  return (
    route.requestModes.find((mode) => normalized.startsWith(mode.mediaType.toLowerCase())) ||
    route.requestModes[0] ||
    null
  );
}

function selectResponseMode(route, url, req, body) {
  const explicit = url.searchParams.get("__mockMediaType");
  const explicitStatus = url.searchParams.get("__mockResponseStatus");
  if (explicit || explicitStatus) {
    const selected = route.responseModes.find(
      (mode) =>
        (!explicit || mode.mediaType === explicit) &&
        (!explicitStatus || mode.statusCode === explicitStatus),
    );
    if (selected) return selected;
  }
  const selectorPath = route.streamSelector
    ? String(route.streamSelector.wireName).split(".").filter(Boolean)
    : [];
  if (
    selectorPath.length > 0 &&
    body &&
    readAtPath(body, selectorPath) === route.streamSelector.value
  ) {
    const selected = route.responseModes.find((mode) => mode.decoderKind === "sse");
    if (selected) return selected;
  }
  const accept = String(req.headers.accept || "");
  if (accept) {
    const selected = route.responseModes.find(
      (mode) => mode.mediaType && accept.includes(mode.mediaType),
    );
    if (selected) return selected;
  }
  return route.responseModes[route.defaultResponseIndex] || route.responseModes[0];
}

function parseCookies(header) {
  const cookies = new Map();
  for (const pair of String(header || "").split(";")) {
    const index = pair.indexOf("=");
    if (index < 0) continue;
    const name = pair.slice(0, index).trim();
    let value = pair.slice(index + 1).trim();
    try {
      value = decodeURIComponent(value);
    } catch {
      // A value that is not percent-encoded is read as sent.
    }
    cookies.set(name, [...(cookies.get(name) || []), value]);
  }
  return cookies;
}

// An exploded object cookie arrives as one pair per member; they are folded
// back into the exploded simple form, "k=v,k2=v2". With no declared members
// its pairs cannot be told apart from other cookies, so it is never found.
function cookieValue(cookies, parameter) {
  if (parameter.shape === "object" && parameter.explode && !parameter.jsonContent) {
    const members = parameter.members.filter((member) => cookies.has(member));
    return members.length
      ? members.map((member) => member + "=" + cookies.get(member)[0]).join(",")
      : undefined;
  }
  return cookies.get(parameter.wireName)?.join(",");
}

function isUnlocatableCookie(parameter) {
  return (
    parameter.shape === "object" &&
    parameter.explode &&
    !parameter.jsonContent &&
    parameter.members.length === 0
  );
}

const TEMPORAL_WIRE_VALUE = {
  date: /^\d{4}-\d{2}-\d{2}$/,
  "date-time": /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/i,
};

// Whether a sent value decodes to its declared shape. JSON content must parse to
// it. Simple-style text never parses as a JSON array or object: an array is its
// items comma-joined, an object "k,v" pairs, or "k=v" members when exploded. A
// date or date-time value, or each array item, is in its RFC 3339 form.
function wireValueMatches(parameter, value) {
  const text = String(value);
  let decoded;
  let parsed = true;
  try {
    decoded = JSON.parse(text);
  } catch {
    parsed = false;
  }
  const isObject = decoded !== null && typeof decoded === "object" && !Array.isArray(decoded);
  if (parameter.jsonContent) {
    if (!parsed) return false;
    if (parameter.shape === "object") return isObject;
    return parameter.shape !== "array" || Array.isArray(decoded);
  }
  if (parameter.format)
    return text.split(",").every((part) => TEMPORAL_WIRE_VALUE[parameter.format].test(part));
  if (parameter.shape === "scalar" || text === "") return true;
  if (Array.isArray(decoded) || isObject) return false;
  if (parameter.shape === "array") return true;
  const parts = text.split(",");
  const isMember = (name) => parameter.members.length === 0 || parameter.members.includes(name);
  return parameter.explode
    ? parts.every((part) => part.includes("=") && isMember(part.slice(0, part.indexOf("="))))
    : parts.length % 2 === 0 && parts.every((part, index) => index % 2 === 1 || isMember(part));
}

function sendValidationError(res, details) {
  sendMode(
    res,
    {
      decoderKind: "json",
      mediaType: "application/json",
      example: { error: "Validation failed", details, statusCode: 422 },
    },
    422,
  );
}

const server = createServer(async (req, res) => {
  const method = String(req.method || "GET").toUpperCase();
  const url = new URL(req.url || "/", "http://localhost");
  if (method === "GET" && url.pathname === "/__routes") {
    sendMode(res, {
      decoderKind: "json",
      mediaType: "application/json",
      example: compiled.map((route) => ({
        operationId: route.operationId,
        method: route.method,
        path: route.pathTemplate,
        responseModes: route.responseModes.map((mode) => mode.mediaType),
      })),
    });
    return;
  }

  const routingPath = decodeRoutingPath(url.pathname);
  const route = compiled.find(
    (candidate) =>
      candidate.method === method &&
      candidate.regex.test(routingPath) &&
      (candidate.literalQuery || []).every(([name, value]) =>
        url.searchParams.getAll(name).includes(value),
      ),
  );
  if (!route) {
    sendMode(
      res,
      {
        decoderKind: "json",
        mediaType: "application/json",
        example: { error: "No mock route for " + method + " " + url.pathname, statusCode: 404 },
      },
      404,
    );
    return;
  }

  const missingQuery = route.queryParameters
    .filter((parameter) => parameter.required && !url.searchParams.has(parameter.wireName))
    .map((parameter) => ({
      field: parameter.wireName,
      type: "required",
      message: "missing required query parameter",
    }));
  const missingHeaders = route.headerParameters
    .filter(
      (parameter) =>
        parameter.required && req.headers[parameter.wireName.toLowerCase()] === undefined,
    )
    .map((parameter) => ({
      field: parameter.wireName,
      type: "required",
      message: "missing required header",
    }));
  const cookies = parseCookies(req.headers.cookie);
  const missingCookies = route.cookieParameters
    .filter(
      (parameter) =>
        parameter.required &&
        !isUnlocatableCookie(parameter) &&
        cookieValue(cookies, parameter) === undefined,
    )
    .map((parameter) => ({
      field: parameter.wireName,
      type: "required",
      message: "missing required cookie",
    }));
  const malformed = [
    ...route.queryParameters
      .filter((parameter) => parameter.jsonContent)
      .map((parameter) => [
        parameter,
        url.searchParams.get(parameter.wireName) ?? undefined,
        "query parameter",
      ]),
    ...route.queryParameters
      .filter(
        (parameter) =>
          parameter.format && !parameter.jsonContent && url.searchParams.has(parameter.wireName),
      )
      .map((parameter) => [
        parameter,
        url.searchParams.getAll(parameter.wireName).join(","),
        "query parameter",
      ]),
    ...route.headerParameters.map((parameter) => [
      parameter,
      req.headers[parameter.wireName.toLowerCase()],
      "header",
    ]),
    ...route.cookieParameters.map((parameter) => [
      parameter,
      cookieValue(cookies, parameter),
      "cookie",
    ]),
  ]
    .filter(([parameter, value]) => value !== undefined && !wireValueMatches(parameter, value))
    .map(([parameter, value, location]) => ({
      field: parameter.wireName,
      type: "format",
      message: "malformed " + location + " value " + JSON.stringify(value),
    }));
  if (missingQuery.length || missingHeaders.length || missingCookies.length || malformed.length) {
    sendValidationError(res, [...missingQuery, ...missingHeaders, ...missingCookies, ...malformed]);
    return;
  }

  const contentType = String(req.headers["content-type"] || "");
  const rawBody = await readRawBody(req);
  const requestMode = selectRequestMode(route, contentType);
  const body = parseBody(rawBody, contentType, requestMode);
  if (requestMode?.required && body === null) {
    sendValidationError(res, [
      { field: "body", type: "required", message: "missing required request body" },
    ]);
    return;
  }
  const records = requestMode?.encoderKind === "ndjson" && Array.isArray(body) ? body : [body];
  // XML and other raw bodies arrive unparsed, so they have no fields to check.
  const missingBody = (Buffer.isBuffer(body) ? [] : requestMode?.requiredFields || [])
    .filter((field) =>
      records.some(
        (record) => !record || typeof record !== "object" || record[field] === undefined,
      ),
    )
    .map((field) => ({ field, type: "required", message: "missing required body field" }));
  if (missingBody.length) {
    sendValidationError(res, missingBody);
    return;
  }

  const forcedStatus = url.searchParams.get("__mockStatus");
  if (forcedStatus) {
    const modes = route.errorResponses[forcedStatus];
    const requestedType = url.searchParams.get("__mockMediaType");
    const mode = modes?.find((candidate) => candidate.mediaType === requestedType) ||
      modes?.[0] || {
        decoderKind: "json",
        mediaType: "application/json",
        example: {
          error: "Forced status " + forcedStatus,
          statusCode: Number(forcedStatus) || 500,
        },
      };
    sendMode(res, mode, Number(forcedStatus) || 500);
    return;
  }

  const pathMatch = route.regex.exec(routingPath) || [];
  const pathValues = Object.fromEntries(
    route.pathParams.map((name, index) => [
      name,
      decodeURIComponent(pathMatch.groups?.["sdkPath" + index] || ""),
    ]),
  );
  const selected = selectResponseMode(route, url, req, body);
  if (!selected) {
    const firstError = Object.entries(route.errorResponses || {})[0];
    if (firstError && firstError[1]?.[0]) {
      sendMode(res, firstError[1][0], Number(firstError[0]) || 500);
      return;
    }
    sendMode(res, { decoderKind: "empty", mediaType: null, example: null }, 204);
    return;
  }
  if (
    selected.decoderKind === "json" &&
    selected.hasAuthoredExample !== true &&
    selected.example &&
    typeof selected.example === "object" &&
    !Array.isArray(selected.example)
  ) {
    const example = { ...selected.example };
    for (const [key, value] of Object.entries(pathValues))
      if (key in example && echoable(example[key], value)) example[key] = value;
    if (body && typeof body === "object" && !Buffer.isBuffer(body)) {
      for (const [key, value] of Object.entries(body))
        if (key in example && echoable(example[key], value)) example[key] = value;
    }
    sendMode(res, { ...selected, example });
    return;
  }
  sendMode(res, selected);
});

server.listen(PORT, "127.0.0.1", () => {
  const address = server.address();
  process.stdout.write(
    JSON.stringify({ port: address.port, routes: compiled.length, title: META.title }) + "\n",
  );
});

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => server.close(() => process.exit(0)));
}
