#!/usr/bin/env node

// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

// AUTO-GENERATED. Exercises every success response mode and the authored error examples.
import { spawn } from "node:child_process";
import { readFileSync } from "node:fs";

const ROUTES = JSON.parse(readFileSync(new URL("./mock-routes.json", import.meta.url), "utf8"));
let server;
let stderr = "";
let checks = 0;
let testedResponseModes = 0;

// One JSON record per line; a JSON text sequence also starts each with RS.
function jsonRecord(mediaType, value) {
  return (
    (/^application\/json-seq/i.test(mediaType || "") ? "\x1e" : "") + JSON.stringify(value) + "\n"
  );
}

function assert(condition, message) {
  checks += 1;
  if (!condition) throw new Error(message);
}

// Mirrors the server's echo rule: only scalars are echoed back, because a
// request and a response field that share a name need not share a shape.
function echoable(existing, incoming) {
  const scalar = (value) => value === null || typeof value !== "object";
  if (!scalar(existing) || !scalar(incoming)) return false;
  // Same JSON type, too. VideoResource.seconds is a string on the way out and
  // a number on the way in; echoing across that emits a body the response
  // schema does not describe.
  return typeof existing === typeof incoming;
}

function representativeMatches(actual, expected) {
  if (expected === null || typeof expected !== "object") return Object.is(actual, expected);
  if (Array.isArray(expected)) {
    return (
      Array.isArray(actual) &&
      actual.length === expected.length &&
      expected.every((value, index) => representativeMatches(actual[index], value))
    );
  }
  return (
    actual !== null &&
    typeof actual === "object" &&
    Object.entries(expected).every(([key, value]) => representativeMatches(actual[key], value))
  );
}

function startServer() {
  return new Promise((resolve, reject) => {
    server = spawn(process.execPath, [new URL("./mock-server.mjs", import.meta.url).pathname], {
      stdio: ["ignore", "pipe", "pipe"],
    });
    server.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });
    server.once("error", reject);
    server.once("exit", (code) => {
      if (code && code !== 0) reject(new Error("mock server exited " + code + ": " + stderr));
    });
    server.stdout.once("data", (chunk) => {
      try {
        resolve(JSON.parse(chunk.toString().trim()).port);
      } catch (error) {
        reject(error);
      }
    });
  });
}

function serializeQuery(url, parameter) {
  const value = parameter.example;
  if (parameter.jsonContent) {
    url.searchParams.set(parameter.wireName, JSON.stringify(value));
    return;
  }
  if (Array.isArray(value)) {
    if (parameter.style === "form" && parameter.explode) {
      for (const item of value) url.searchParams.append(parameter.wireName, String(item));
    } else {
      const separator =
        parameter.style === "spaceDelimited"
          ? " "
          : parameter.style === "pipeDelimited"
            ? "|"
            : ",";
      url.searchParams.set(parameter.wireName, value.map(String).join(separator));
    }
    return;
  }
  url.searchParams.set(parameter.wireName, String(value ?? ""));
}

// The simple-style text of a header or cookie value.
function simpleText(parameter, value) {
  if (parameter.jsonContent) return JSON.stringify(value);
  if (Array.isArray(value)) return value.map(String).join(",");
  if (value !== null && typeof value === "object") {
    return Object.entries(value)
      .map(([key, member]) => key + (parameter.explode ? "=" : ",") + String(member))
      .join(",");
  }
  return String(value ?? "value");
}

function cookieHeader(parameters) {
  const pairs = [];
  for (const parameter of parameters) {
    const value = parameter.example;
    const add = (name, text) => pairs.push(name + "=" + encodeURIComponent(text));
    if (parameter.explode && !parameter.jsonContent && Array.isArray(value)) {
      for (const item of value) add(parameter.wireName, String(item));
    } else if (
      parameter.explode &&
      !parameter.jsonContent &&
      value !== null &&
      typeof value === "object"
    ) {
      for (const [key, member] of Object.entries(value)) add(key, String(member));
    } else {
      add(parameter.wireName, simpleText({ ...parameter, explode: false }, value));
    }
  }
  return pairs.join("; ");
}

function requestBody(mode) {
  if (!mode) return { headers: {}, body: undefined };
  if (!mode.required && (mode.example === null || mode.example === undefined)) {
    return { headers: {}, body: undefined };
  }
  if (mode.encoderKind === "json") {
    return { headers: { "content-type": mode.mediaType }, body: JSON.stringify(mode.example) };
  }
  if (mode.encoderKind === "form") {
    return {
      headers: { "content-type": mode.mediaType },
      body: new URLSearchParams(mode.example || {}),
    };
  }
  if (mode.encoderKind === "multipart") {
    const form = new FormData();
    for (const field of mode.fields) {
      const raw = mode.example?.[field.wireName];
      const values = field.repeated && Array.isArray(raw) ? raw : [raw];
      for (const value of values) {
        if (field.partKind === "file") {
          form.append(
            field.wireName,
            new Blob([String(value ?? "file")], {
              type: field.contentType || "application/octet-stream",
            }),
            "mock.bin",
          );
        } else if (field.partKind === "json") {
          form.append(
            field.wireName,
            new Blob([JSON.stringify(value)], { type: field.contentType || "application/json" }),
          );
        } else {
          form.append(field.wireName, String(value ?? ""));
        }
      }
    }
    return { headers: {}, body: form };
  }
  if (mode.encoderKind === "ndjson") {
    const records = Array.isArray(mode.example) ? mode.example : [mode.example];
    return {
      headers: { "content-type": mode.mediaType },
      body: records.map((record) => jsonRecord(mode.mediaType, record)).join(""),
    };
  }
  const body = typeof mode.example === "string" ? mode.example : JSON.stringify(mode.example);
  return { headers: { "content-type": mode.mediaType }, body };
}

async function probe(baseUrl, route, responseMode, requestMode, forcedStatus) {
  let pathname = route.pathTemplate;
  const pathValues = {};
  for (const parameter of route.pathParameters) {
    const value = parameter.routeRepresentative ?? parameter.example ?? "id";
    pathValues[parameter.wireName] = String(value);
    pathname = pathname.replace("{" + parameter.wireName + "}", encodeURIComponent(String(value)));
  }
  const url = new URL(pathname, baseUrl);
  for (const parameter of route.queryParameters.filter((item) => item.required))
    serializeQuery(url, parameter);
  if (responseMode.mediaType) url.searchParams.set("__mockMediaType", responseMode.mediaType);
  if (!forcedStatus) url.searchParams.set("__mockResponseStatus", responseMode.statusCode);
  if (forcedStatus) url.searchParams.set("__mockStatus", forcedStatus);
  const init = requestBody(requestMode);
  for (const parameter of route.headerParameters.filter((item) => item.required)) {
    init.headers[parameter.wireName] = simpleText(parameter, parameter.example);
  }
  const cookies = cookieHeader(route.cookieParameters.filter((item) => item.required));
  if (cookies) init.headers.cookie = cookies;
  const response = await fetch(url, {
    method: route.method,
    headers: init.headers,
    body: init.body,
  });
  let expectedExample = responseMode.example;
  if (
    !forcedStatus &&
    responseMode.hasAuthoredExample !== true &&
    expectedExample &&
    typeof expectedExample === "object" &&
    !Array.isArray(expectedExample)
  ) {
    expectedExample = structuredClone(expectedExample);
    for (const [key, value] of Object.entries(pathValues)) {
      if (key in expectedExample && echoable(expectedExample[key], value))
        expectedExample[key] = value;
    }
    // The server echoes only the bodies it parses into fields; an XML or other
    // raw body reaches it as bytes.
    if (
      ["json", "form", "multipart"].includes(requestMode?.encoderKind) &&
      requestMode.example &&
      typeof requestMode.example === "object"
    ) {
      for (const [key, value] of Object.entries(requestMode.example)) {
        if (key in expectedExample && echoable(expectedExample[key], value))
          expectedExample[key] = value;
      }
    }
  }
  const expectedStatus = forcedStatus
    ? Number(forcedStatus) || 500
    : Number(responseMode.statusCode) || 200;
  assert(
    response.status === expectedStatus,
    route.operationId + " returned " + response.status + ", expected " + expectedStatus,
  );
  assert(
    response.headers.get("x-request-id") === "req_mock_123",
    route.operationId + " omitted request ID",
  );
  if (responseMode.mediaType) {
    assert(
      String(response.headers.get("content-type") || "")
        .toLowerCase()
        .startsWith(responseMode.mediaType.toLowerCase()),
      route.operationId + " returned the wrong content type for " + responseMode.mediaType,
    );
  }
  if (responseMode.decoderKind === "empty") {
    assert(
      (await response.arrayBuffer()).byteLength === 0,
      route.operationId + " empty mode returned bytes",
    );
  } else if (responseMode.decoderKind === "json") {
    const payload = await response.text();
    let decoded;
    try {
      decoded = JSON.parse(payload);
    } catch (error) {
      throw new Error(
        route.operationId +
          " returned invalid JSON for " +
          responseMode.statusCode +
          " " +
          responseMode.mediaType +
          ": " +
          String(error),
      );
    }
    assert(
      representativeMatches(decoded, expectedExample),
      route.operationId + " did not preserve authored JSON response fields",
    );
    checks += 1;
  } else if (responseMode.decoderKind === "sse") {
    const text = await response.text();
    assert(
      text.includes("data: ") && text.includes("data: [DONE]"),
      route.operationId + " returned invalid SSE",
    );
  } else if (responseMode.decoderKind === "bytes") {
    const actual = Buffer.from(await response.arrayBuffer());
    const expected = Buffer.from(responseMode.bodyBase64 || "", "base64");
    assert(
      actual.equals(expected),
      route.operationId + " returned different binary response bytes",
    );
  } else if (responseMode.decoderKind === "ndjson") {
    assert(
      (await response.text()) === jsonRecord(responseMode.mediaType, responseMode.example),
      route.operationId + " returned a different NDJSON record",
    );
  } else {
    assert(
      (await response.text()) === String(responseMode.example ?? ""),
      route.operationId + " returned different authored text",
    );
  }
}

const port = await startServer();
const baseUrl = "http://127.0.0.1:" + port;
try {
  const discovery = await fetch(baseUrl + "/__routes");
  const discovered = await discovery.json();
  assert(discovered.length === ROUTES.length, "route discovery count mismatch");
  const testedRouteIds = new Set();
  for (const route of ROUTES) {
    const requestModes = route.requestModes.length ? route.requestModes : [null];
    // A spec without examples still has a schema-generated body for every
    // success mode, and that body is what the SDK has to decode.
    const successModes = route.responseModes;
    const authoredErrorEntries = Object.entries(route.errorResponses)
      .map(([status, modes]) => [status, modes.filter((mode) => mode.hasAuthoredExample === true)])
      .filter(([, modes]) => modes.length > 0);
    const modeCount =
      successModes.length +
      authoredErrorEntries.reduce((total, [, modes]) => total + modes.length, 0);
    if (modeCount > 0) testedRouteIds.add(route.operationId);
    testedResponseModes += modeCount;
    for (const requestMode of requestModes) {
      for (const mode of successModes) await probe(baseUrl, route, mode, requestMode, null);
      for (const [status, modes] of authoredErrorEntries) {
        for (const mode of modes) await probe(baseUrl, route, mode, requestMode, status);
      }
    }
  }
  process.stdout.write(
    JSON.stringify({
      routes: ROUTES.length,
      testedRoutes: testedRouteIds.size,
      testedResponseModes,
      skippedRoutes: ROUTES.length - testedRouteIds.size,
      checks,
    }) + "\n",
  );
} finally {
  server.kill("SIGTERM");
}
