// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import { encodePathSegment, multipartJson, queryValue, sdkRequest } from "../dist/index.js";
import { installFakeTransport } from "./fake-transport.mjs";

test("encodes one path segment", () => {
  assert.equal(encodePathSegment("/ ?#%雪"), "%2F%20%3F%23%25%E9%9B%AA");
});

test("serializes query arrays by style and explode", () => {
  assert.deepEqual(queryValue(["a", "雪"], "form", true), ["a", "雪"]);
  assert.equal(queryValue(["a", "b"], "form", false), "a,b");
});

test("retains multipart metadata", () => {
  assert.deepEqual(multipartJson({ nested: true }), {
    data: '{"nested":true}',
    contentType: "application/json",
  });
});

test("executes the request layer through a fake transport", async () => {
  const transport = installFakeTransport((seen) => {
    assert.equal(seen.url, "https://example.test/probe?item=a&item=%E9%9B%AA");
    assert.equal(seen.method, "GET");
    return {
      status: 200,
      headers: { "content-type": "application/json", "x-request-id": "fake-id" },
      body: '{"ok":true}',
    };
  });
  try {
    const response = await sdkRequest({
      method: "GET",
      path: "/probe",
      operationId: "probe",
      query: { item: ["a", "雪"] },
      responseDecoder: "json",
      config: { baseUrl: "https://example.test" },
    });
    assert.deepEqual(response.data, { ok: true });
    assert.equal(response.requestId, "fake-id");
  } finally {
    transport.restore();
  }
});
