// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `V1BadgeData` API schema.
 */
export interface V1BadgeData {
  /**
   * Optional `string` value serialized in the `color` wire field.
   */
  color?: string;
  /**
   * Optional `string` value serialized in the `label` wire field.
   */
  label?: string;
  /**
   * Optional `string` value serialized in the `message` wire field.
   */
  message?: string;
  /**
   * Optional `integer` value serialized in the `schemaVersion` wire field.
   */
  schemaVersion?: number;
}
