// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ModelsDiagnostics` API schema.
 */
export interface ModelsDiagnostics {
  /**
   * Optional `string` value serialized in the `architecture` wire field.
   */
  architecture?: string;
  /**
   * Optional `string` value serialized in the `cli_version` wire field.
   */
  cliVersion?: string;
  /**
   * Optional `integer` value serialized in the `id` wire field.
   */
  id?: number;
  /**
   * Optional `string` value serialized in the `logs` wire field.
   */
  logs?: string;
  /**
   * Optional `string` value serialized in the `platform` wire field.
   */
  platform?: string;
  /**
   * Optional `string` value serialized in the `plugin` wire field.
   */
  plugin?: string;
  /**
   * Optional `string` value serialized in the `stacktrace` wire field.
   */
  stacktrace?: string;
}
