// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ModelsHeartbeat` API schema.
 */
export interface ModelsHeartbeat {
  /**
   * Optional `integer` value serialized in the `ai_input_tokens` wire field.
   */
  aiInputTokens?: number;
  /**
   * Optional `integer` value serialized in the `ai_line_changes` wire field.
   */
  aiLineChanges?: number;
  /**
   * Optional `integer` value serialized in the `ai_output_tokens` wire field.
   */
  aiOutputTokens?: number;
  /**
   * Optional `integer` value serialized in the `ai_prompt_length` wire field.
   */
  aiPromptLength?: number;
  /**
   * Optional `string` value serialized in the `ai_session` wire field.
   */
  aiSession?: string;
  /**
   * Optional `string` value serialized in the `branch` wire field.
   */
  branch?: string;
  /**
   * Optional `string` value serialized in the `category` wire field.
   */
  category?: string;
  /**
   * https://gorm.io/docs/conventions.html#CreatedAt
   */
  createdAt?: number;
  /**
   * Optional `integer` value serialized in the `cursorpos` wire field.
   */
  cursorpos?: number;
  /**
   * ignored because editor might be parsed differently by wakatime
   */
  editor?: string;
  /**
   * Optional `string` value serialized in the `entity` wire field.
   */
  entity?: string;
  /**
   * Optional `integer` value serialized in the `human_line_changes` wire field.
   */
  humanLineChanges?: number;
  /**
   * Optional `boolean` value serialized in the `is_write` wire field.
   */
  isWrite?: boolean;
  /**
   * Optional `string` value serialized in the `language` wire field.
   */
  language?: string;
  /**
   * Optional `integer` value serialized in the `line_additions` wire field.
   */
  lineAdditions?: number;
  /**
   * Optional `integer` value serialized in the `line_deletions` wire field.
   */
  lineDeletions?: number;
  /**
   * Optional `integer` value serialized in the `lineno` wire field.
   */
  lineno?: number;
  /**
   * Optional `integer` value serialized in the `lines` wire field.
   */
  lines?: number;
  /**
   * ignored because wakatime api doesn't return machines currently
   */
  machine?: string;
  /**
   * ignored because os might be parsed differently by wakatime
   */
  operatingSystem?: string;
  /**
   * Optional `string` value serialized in the `project` wire field.
   */
  project?: string;
  /**
   * Optional `integer` value serialized in the `project_root_count` wire field.
   */
  projectRootCount?: number;
  /**
   * note: on sqlite, table will have an additional column `time_real`, introduced "manually" by migration 20260111
   * see https://github.com/muety/wakapi/issues/882 for details
   */
  time?: number;
  /**
   * Optional `string` value serialized in the `type` wire field.
   */
  type?: string;
  /**
   * Optional `string` value serialized in the `user_agent` wire field.
   */
  userAgent?: string;
}

/**
 * Typed representation of the `V1HeartbeatEntry` API schema.
 */
export interface V1HeartbeatEntry {
  /**
   * Optional `integer` value serialized in the `ai_input_tokens` wire field.
   */
  aiInputTokens?: number;
  /**
   * Optional `integer` value serialized in the `ai_line_changes` wire field.
   */
  aiLineChanges?: number;
  /**
   * Optional `integer` value serialized in the `ai_output_tokens` wire field.
   */
  aiOutputTokens?: number;
  /**
   * Optional `integer` value serialized in the `ai_prompt_length` wire field.
   */
  aiPromptLength?: number;
  /**
   * Optional `string` value serialized in the `ai_session` wire field.
   */
  aiSession?: string;
  /**
   * Optional `string` value serialized in the `branch` wire field.
   */
  branch?: string;
  /**
   * Optional `string` value serialized in the `category` wire field.
   */
  category?: string;
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `integer` value serialized in the `cursorpos` wire field.
   */
  cursorpos?: number;
  /**
   * Optional `string` value serialized in the `entity` wire field.
   */
  entity?: string;
  /**
   * Optional `integer` value serialized in the `human_line_changes` wire field.
   */
  humanLineChanges?: number;
  /**
   * Optional `string` value serialized in the `id` wire field.
   */
  id?: string;
  /**
   * Optional `boolean` value serialized in the `is_write` wire field.
   */
  isWrite?: boolean;
  /**
   * Optional `string` value serialized in the `language` wire field.
   */
  language?: string;
  /**
   * Optional `integer` value serialized in the `line_additions` wire field.
   */
  lineAdditions?: number;
  /**
   * Optional `integer` value serialized in the `line_deletions` wire field.
   */
  lineDeletions?: number;
  /**
   * Optional `integer` value serialized in the `lineno` wire field.
   */
  lineno?: number;
  /**
   * Optional `integer` value serialized in the `lines` wire field.
   */
  lines?: number;
  /**
   * Optional `string` value serialized in the `machine_name_id` wire field.
   */
  machineNameId?: string;
  /**
   * Optional `string` value serialized in the `project` wire field.
   */
  project?: string;
  /**
   * Optional `number` value serialized in the `time` wire field.
   */
  time?: number;
  /**
   * Optional `string` value serialized in the `type` wire field.
   */
  type?: string;
  /**
   * Optional `string` value serialized in the `user_agent_id` wire field.
   */
  userAgentId?: string;
  /**
   * Optional `string` value serialized in the `user_id` wire field.
   */
  userId?: string;
}

/**
 * Typed representation of the `V1HeartbeatsResult` API schema.
 */
export interface V1HeartbeatsResult {
  /**
   * Optional array value serialized in the `data` wire field.
   */
  data?: V1HeartbeatEntry[];
  /**
   * Optional `string` value serialized in the `end` wire field.
   */
  end?: string;
  /**
   * Optional `string` value serialized in the `start` wire field.
   */
  start?: string;
  /**
   * Optional `string` value serialized in the `timezone` wire field.
   */
  timezone?: string;
}
