// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ModelsSummary` API schema.
 */
export interface ModelsSummary {
  /**
   * branches are not persisted, but calculated at runtime in case a project Filter is applied
   */
  branches?: ModelsSummaryItem[];
  /**
   * Optional array value serialized in the `categories` wire field.
   */
  categories?: ModelsSummaryItem[];
  /**
   * Optional array value serialized in the `editors` wire field.
   */
  editors?: ModelsSummaryItem[];
  /**
   * entities are not persisted, but calculated at runtime in case a project Filter is applied
   */
  entities?: ModelsSummaryItem[];
  /**
   * filled by gorm if not set, see https://gorm.io/docs/conventions.html#CreatedAt
   */
  from?: string;
  /**
   * labels are not persisted, but calculated at runtime, i.e. when summary is retrieved
   */
  labels?: ModelsSummaryItem[];
  /**
   * Optional array value serialized in the `languages` wire field.
   */
  languages?: ModelsSummaryItem[];
  /**
   * Optional array value serialized in the `machines` wire field.
   */
  machines?: ModelsSummaryItem[];
  /**
   * Optional array value serialized in the `operating_systems` wire field.
   */
  operatingSystems?: ModelsSummaryItem[];
  /**
   * Previously, all the following properties created a cascade foreign key constraint on the summary_items table
   * back to this summary table resulting in 5 identical foreign key constraints on the summary_items table.
   * This is not a problem for PostgreSQL, MySQL and SQLite, but for MSSQL (not supported anymore though), which complains about circular cascades on
   * update/delete between these two tables. All of these created foreign key constraints are identical, so only one constraint is enough.
   * MySQL will create a foreign key constraint for every property referencing other structs, even no constraint is specified in tags.
   * So explicitly set gorm:"-" in all other properties to avoid creating duplicate foreign key constraints
   */
  projects?: ModelsSummaryItem[];
  /**
   * filled by gorm if not set, see https://gorm.io/docs/conventions.html#CreatedAt
   */
  to?: string;
  /**
   * Optional `string` value serialized in the `user_id` wire field.
   */
  userId?: string;
}

/**
 * Typed representation of the `ModelsSummaryItem` API schema.
 */
export interface ModelsSummaryItem {
  /**
   * Optional `string` value serialized in the `key` wire field.
   */
  key?: string;
  /**
   * Optional `integer` value serialized in the `total` wire field.
   */
  total?: number;
}
