// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type {
  V1SummariesCumulativeTotal,
  V1SummariesDailyAverage,
  V1SummariesData,
} from "./wakatime.part001";

/**
 * Typed representation of the `V1SummariesViewModel` API schema.
 */
export interface V1SummariesViewModel {
  /**
   * Optional object value serialized in the `cumulative_total` wire field.
   */
  cumulativeTotal?: V1SummariesCumulativeTotal;
  /**
   * Optional object value serialized in the `daily_average` wire field.
   */
  dailyAverage?: V1SummariesDailyAverage;
  /**
   * Optional array value serialized in the `data` wire field.
   */
  data?: V1SummariesData[];
  /**
   * Optional `string` value serialized in the `end` wire field.
   */
  end?: string;
  /**
   * Optional `string` value serialized in the `start` wire field.
   */
  start?: string;
}

/**
 * Typed representation of the `V1User` API schema.
 */
export interface V1User {
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `string` value serialized in the `display_name` wire field.
   */
  displayName?: string;
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional `string` value serialized in the `full_name` wire field.
   */
  fullName?: string;
  /**
   * Optional `string` value serialized in the `id` wire field.
   */
  id?: string;
  /**
   * Optional `boolean` value serialized in the `is_email_confirmed` wire field.
   */
  isEmailConfirmed?: boolean;
  /**
   * Optional `boolean` value serialized in the `is_email_public` wire field.
   */
  isEmailPublic?: boolean;
  /**
   * Optional `string` value serialized in the `last_heartbeat_at` wire field.
   */
  lastHeartbeatAt?: string;
  /**
   * Optional `string` value serialized in the `last_plugin_name` wire field.
   */
  lastPluginName?: string;
  /**
   * Optional `string` value serialized in the `last_project` wire field.
   */
  lastProject?: string;
  /**
   * Optional `string` value serialized in the `modified_at` wire field.
   */
  modifiedAt?: string;
  /**
   * Optional `string` value serialized in the `photo` wire field.
   */
  photo?: string;
  /**
   * Optional `string` value serialized in the `timezone` wire field.
   */
  timezone?: string;
  /**
   * Optional `string` value serialized in the `username` wire field.
   */
  username?: string;
  /**
   * Optional `string` value serialized in the `website` wire field.
   */
  website?: string;
}

/**
 * Typed representation of the `V1UserAgentEntry` API schema.
 */
export interface V1UserAgentEntry {
  /**
   * Optional `string` value serialized in the `editor` wire field.
   */
  editor?: string;
  /**
   * Optional `string` value serialized in the `first_seen` wire field.
   */
  firstSeen?: string;
  /**
   * Optional `string` value serialized in the `id` wire field.
   */
  id?: string;
  /**
   * currently not implemented
   */
  isBrowserExtension?: boolean;
  /**
   * currently not implemented
   */
  isDesktopApp?: boolean;
  /**
   * Optional `string` value serialized in the `last_seen` wire field.
   */
  lastSeen?: string;
  /**
   * Optional `string` value serialized in the `os` wire field.
   */
  os?: string;
  /**
   * Optional `string` value serialized in the `value` wire field.
   */
  value?: string;
  /**
   * currently not implemented
   */
  version?: string;
}

/**
 * Typed representation of the `V1UserAgentsViewModel` API schema.
 */
export interface V1UserAgentsViewModel {
  /**
   * Optional array value serialized in the `data` wire field.
   */
  data?: V1UserAgentEntry[];
  /**
   * Optional `integer` value serialized in the `total_pages` wire field.
   */
  totalPages?: number;
}

/**
 * Typed representation of the `V1UserViewModel` API schema.
 */
export interface V1UserViewModel {
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: V1User;
}
