// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { V1User } from "./wakatime.part002";

/**
 * Typed representation of the `V1AllTimeData` API schema.
 */
export interface V1AllTimeData {
  /**
   * true if the stats are up to date; when false, a 202 response code is returned and stats will be refreshed soon>
   */
  isUpToDate?: boolean;
  /**
   * Optional object value serialized in the `range` wire field.
   */
  range?: V1AllTimeRange;
  /**
   * total time logged since account created as human readable string>
   */
  text?: string;
  /**
   * total number of seconds logged since account created
   */
  totalSeconds?: number;
}

/**
 * Typed representation of the `V1AllTimeRange` API schema.
 */
export interface V1AllTimeRange {
  /**
   * Optional `string` value serialized in the `end` wire field.
   */
  end?: string;
  /**
   * Optional `string` value serialized in the `end_date` wire field.
   */
  endDate?: string;
  /**
   * Optional `string` value serialized in the `start` wire field.
   */
  start?: string;
  /**
   * Optional `string` value serialized in the `start_date` wire field.
   */
  startDate?: string;
  /**
   * Optional `string` value serialized in the `timezone` wire field.
   */
  timezone?: string;
}

/**
 * Typed representation of the `V1AllTimeViewModel` API schema.
 */
export interface V1AllTimeViewModel {
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: V1AllTimeData;
}

/**
 * Typed representation of the `V1LeadersCurrentUser` API schema.
 */
export interface V1LeadersCurrentUser {
  /**
   * Optional `integer` value serialized in the `page` wire field.
   */
  page?: number;
  /**
   * Optional `integer` value serialized in the `rank` wire field.
   */
  rank?: number;
  /**
   * Optional object value serialized in the `user` wire field.
   */
  user?: V1User;
}

/**
 * Typed representation of the `V1LeadersEntry` API schema.
 */
export interface V1LeadersEntry {
  /**
   * Optional `integer` value serialized in the `rank` wire field.
   */
  rank?: number;
  /**
   * Optional object value serialized in the `running_total` wire field.
   */
  runningTotal?: V1LeadersRunningTotal;
  /**
   * Optional object value serialized in the `user` wire field.
   */
  user?: V1User;
}

/**
 * Typed representation of the `V1LeadersLanguage` API schema.
 */
export interface V1LeadersLanguage {
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `number` value serialized in the `total_seconds` wire field.
   */
  totalSeconds?: number;
}

/**
 * Typed representation of the `V1LeadersRange` API schema.
 */
export interface V1LeadersRange {
  /**
   * Optional `string` value serialized in the `end_date` wire field.
   */
  endDate?: string;
  /**
   * Optional `string` value serialized in the `end_text` wire field.
   */
  endText?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `start_date` wire field.
   */
  startDate?: string;
  /**
   * Optional `string` value serialized in the `start_text` wire field.
   */
  startText?: string;
  /**
   * Optional `string` value serialized in the `text` wire field.
   */
  text?: string;
}

/**
 * Typed representation of the `V1LeadersRunningTotal` API schema.
 */
export interface V1LeadersRunningTotal {
  /**
   * Optional `number` value serialized in the `daily_average` wire field.
   */
  dailyAverage?: number;
  /**
   * Optional `string` value serialized in the `human_readable_daily_average` wire field.
   */
  humanReadableDailyAverage?: string;
  /**
   * Optional `string` value serialized in the `human_readable_total` wire field.
   */
  humanReadableTotal?: string;
  /**
   * Optional array value serialized in the `languages` wire field.
   */
  languages?: V1LeadersLanguage[];
  /**
   * Optional `number` value serialized in the `total_seconds` wire field.
   */
  totalSeconds?: number;
}

/**
 * Typed representation of the `V1LeadersViewModel` API schema.
 */
export interface V1LeadersViewModel {
  /**
   * Optional object value serialized in the `current_user` wire field.
   */
  currentUser?: V1LeadersCurrentUser;
  /**
   * Optional array value serialized in the `data` wire field.
   */
  data?: V1LeadersEntry[];
  /**
   * Optional `string` value serialized in the `language` wire field.
   */
  language?: string;
  /**
   * Optional `integer` value serialized in the `page` wire field.
   */
  page?: number;
  /**
   * Optional object value serialized in the `range` wire field.
   */
  range?: V1LeadersRange;
  /**
   * Optional `integer` value serialized in the `total_pages` wire field.
   */
  totalPages?: number;
}

/**
 * Typed representation of the `V1Project` API schema.
 */
export interface V1Project {
  /**
   * Optional `string` value serialized in the `created_at` wire field.
   */
  createdAt?: string;
  /**
   * Optional `string` value serialized in the `human_readable_last_heartbeat_at` wire field.
   */
  humanReadableLastHeartbeatAt?: string;
  /**
   * Optional `string` value serialized in the `id` wire field.
   */
  id?: string;
  /**
   * Optional `string` value serialized in the `last_heartbeat_at` wire field.
   */
  lastHeartbeatAt?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `urlencoded_name` wire field.
   */
  urlencodedName?: string;
}

/**
 * Typed representation of the `V1ProjectsViewModel` API schema.
 */
export interface V1ProjectsViewModel {
  /**
   * Optional array value serialized in the `data` wire field.
   */
  data?: V1Project[];
}

/**
 * Typed representation of the `V1ProjectViewModel` API schema.
 */
export interface V1ProjectViewModel {
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: V1Project;
}

/**
 * Typed representation of the `V1StatsData` API schema.
 */
export interface V1StatsData {
  /**
   * Optional array value serialized in the `branches` wire field.
   */
  branches?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `categories` wire field.
   */
  categories?: V1SummariesEntry[];
  /**
   * Optional `number` value serialized in the `daily_average` wire field.
   */
  dailyAverage?: number;
  /**
   * Optional `integer` value serialized in the `days_including_holidays` wire field.
   */
  daysIncludingHolidays?: number;
  /**
   * Optional array value serialized in the `editors` wire field.
   */
  editors?: V1SummariesEntry[];
  /**
   * Optional `string` value serialized in the `end` wire field.
   */
  end?: string;
  /**
   * Optional `string` value serialized in the `human_readable_daily_average` wire field.
   */
  humanReadableDailyAverage?: string;
  /**
   * Optional `string` value serialized in the `human_readable_range` wire field.
   */
  humanReadableRange?: string;
  /**
   * Optional `string` value serialized in the `human_readable_total` wire field.
   */
  humanReadableTotal?: string;
  /**
   * Optional `boolean` value serialized in the `is_coding_activity_visible` wire field.
   */
  isCodingActivityVisible?: boolean;
  /**
   * Optional `boolean` value serialized in the `is_other_usage_visible` wire field.
   */
  isOtherUsageVisible?: boolean;
  /**
   * Optional array value serialized in the `languages` wire field.
   */
  languages?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `machines` wire field.
   */
  machines?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `operating_systems` wire field.
   */
  operatingSystems?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `projects` wire field.
   */
  projects?: V1SummariesEntry[];
  /**
   * Optional `string` value serialized in the `range` wire field.
   */
  range?: string;
  /**
   * Optional `string` value serialized in the `start` wire field.
   */
  start?: string;
  /**
   * Optional `string` value serialized in the `status` wire field.
   */
  status?: string;
  /**
   * Optional `string` value serialized in the `timezone` wire field.
   */
  timezone?: string;
  /**
   * Optional `number` value serialized in the `total_seconds` wire field.
   */
  totalSeconds?: number;
  /**
   * Optional `string` value serialized in the `user_id` wire field.
   */
  userId?: string;
  /**
   * Optional `string` value serialized in the `username` wire field.
   */
  username?: string;
}

/**
 * Typed representation of the `V1StatsViewModel` API schema.
 */
export interface V1StatsViewModel {
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: V1StatsData;
}

/**
 * Typed representation of the `V1StatusBarViewModel` API schema.
 */
export interface V1StatusBarViewModel {
  /**
   * Optional `string` value serialized in the `cached_at` wire field.
   */
  cachedAt?: string;
  /**
   * Optional object value serialized in the `data` wire field.
   */
  data?: V1SummariesData;
}

/**
 * Typed representation of the `V1SummariesCumulativeTotal` API schema.
 */
export interface V1SummariesCumulativeTotal {
  /**
   * Optional `string` value serialized in the `decimal` wire field.
   */
  decimal?: string;
  /**
   * Optional `string` value serialized in the `digital` wire field.
   */
  digital?: string;
  /**
   * Optional `number` value serialized in the `seconds` wire field.
   */
  seconds?: number;
  /**
   * Optional `string` value serialized in the `text` wire field.
   */
  text?: string;
}

/**
 * Typed representation of the `V1SummariesDailyAverage` API schema.
 */
export interface V1SummariesDailyAverage {
  /**
   * Optional `integer` value serialized in the `days_including_holidays` wire field.
   */
  daysIncludingHolidays?: number;
  /**
   * Optional `integer` value serialized in the `days_minus_holidays` wire field.
   */
  daysMinusHolidays?: number;
  /**
   * Optional `integer` value serialized in the `holidays` wire field.
   */
  holidays?: number;
  /**
   * Optional `integer` value serialized in the `seconds` wire field.
   */
  seconds?: number;
  /**
   * Optional `integer` value serialized in the `seconds_including_other_language` wire field.
   */
  secondsIncludingOtherLanguage?: number;
  /**
   * Optional `string` value serialized in the `text` wire field.
   */
  text?: string;
  /**
   * Optional `string` value serialized in the `text_including_other_language` wire field.
   */
  textIncludingOtherLanguage?: string;
}

/**
 * Typed representation of the `V1SummariesData` API schema.
 */
export interface V1SummariesData {
  /**
   * Optional array value serialized in the `branches` wire field.
   */
  branches?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `categories` wire field.
   */
  categories?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `dependencies` wire field.
   */
  dependencies?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `editors` wire field.
   */
  editors?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `entities` wire field.
   */
  entities?: V1SummariesEntry[];
  /**
   * Optional object value serialized in the `grand_total` wire field.
   */
  grandTotal?: V1SummariesGrandTotal;
  /**
   * Optional array value serialized in the `languages` wire field.
   */
  languages?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `machines` wire field.
   */
  machines?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `operating_systems` wire field.
   */
  operatingSystems?: V1SummariesEntry[];
  /**
   * Optional array value serialized in the `projects` wire field.
   */
  projects?: V1SummariesEntry[];
  /**
   * Optional object value serialized in the `range` wire field.
   */
  range?: V1SummariesRange;
}

/**
 * Typed representation of the `V1SummariesEntry` API schema.
 */
export interface V1SummariesEntry {
  /**
   * Optional `string` value serialized in the `digital` wire field.
   */
  digital?: string;
  /**
   * Optional `integer` value serialized in the `hours` wire field.
   */
  hours?: number;
  /**
   * Optional `integer` value serialized in the `minutes` wire field.
   */
  minutes?: number;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `number` value serialized in the `percent` wire field.
   */
  percent?: number;
  /**
   * Optional `integer` value serialized in the `seconds` wire field.
   */
  seconds?: number;
  /**
   * Optional `string` value serialized in the `text` wire field.
   */
  text?: string;
  /**
   * Optional `number` value serialized in the `total_seconds` wire field.
   */
  totalSeconds?: number;
}

/**
 * Typed representation of the `V1SummariesGrandTotal` API schema.
 */
export interface V1SummariesGrandTotal {
  /**
   * Optional `string` value serialized in the `digital` wire field.
   */
  digital?: string;
  /**
   * Optional `integer` value serialized in the `hours` wire field.
   */
  hours?: number;
  /**
   * Optional `integer` value serialized in the `minutes` wire field.
   */
  minutes?: number;
  /**
   * Optional `string` value serialized in the `text` wire field.
   */
  text?: string;
  /**
   * Optional `number` value serialized in the `total_seconds` wire field.
   */
  totalSeconds?: number;
}

/**
 * Typed representation of the `V1SummariesRange` API schema.
 */
export interface V1SummariesRange {
  /**
   * Optional `string` value serialized in the `date` wire field.
   */
  date?: string;
  /**
   * Optional `string` value serialized in the `end` wire field.
   */
  end?: string;
  /**
   * Optional `string` value serialized in the `start` wire field.
   */
  start?: string;
  /**
   * Optional `string` value serialized in the `text` wire field.
   */
  text?: string;
  /**
   * Optional `string` value serialized in the `timezone` wire field.
   */
  timezone?: string;
}
