// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  getHeartbeats,
  postHeartbeat3,
  postHeartbeat7,
  postHeartbeat,
  postHeartbeat5,
  postHeartbeat4,
  postHeartbeat8,
  postHeartbeat2,
  postHeartbeat6,
} from "../../dist/methods/heartbeat.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getHeartbeats: {
    route: "getHeartbeats",
    mediaType: null,
    invoke: (bag) => getHeartbeats(config, { date: bag["date"], user: bag["user"] }),
  },
  postHeartbeat3: {
    route: "postHeartbeat3",
    mediaType: "application/json",
    invoke: (bag) =>
      postHeartbeat3(config, {
        aiInputTokens: bag.__body?.["ai_input_tokens"],
        aiLineChanges: bag.__body?.["ai_line_changes"],
        aiOutputTokens: bag.__body?.["ai_output_tokens"],
        aiPromptLength: bag.__body?.["ai_prompt_length"],
        aiSession: bag.__body?.["ai_session"],
        branch: bag.__body?.["branch"],
        category: bag.__body?.["category"],
        createdAt: bag.__body?.["created_at"],
        cursorpos: bag.__body?.["cursorpos"],
        editor: bag.__body?.["editor"],
        entity: bag.__body?.["entity"],
        humanLineChanges: bag.__body?.["human_line_changes"],
        isWrite: bag.__body?.["is_write"],
        language: bag.__body?.["language"],
        lineAdditions: bag.__body?.["line_additions"],
        lineDeletions: bag.__body?.["line_deletions"],
        lineno: bag.__body?.["lineno"],
        lines: bag.__body?.["lines"],
        machine: bag.__body?.["machine"],
        operatingSystem: bag.__body?.["operating_system"],
        project: bag.__body?.["project"],
        projectRootCount: bag.__body?.["project_root_count"],
        time: bag.__body?.["time"],
        ["type"]: bag.__body?.["type"],
        userAgent: bag.__body?.["user_agent"],
        user: bag["user"],
      }),
  },
  postHeartbeat7: {
    route: "postHeartbeat7",
    mediaType: "application/json",
    invoke: (bag) => postHeartbeat7(config, { body: bag.__body, user: bag["user"] }),
  },
  postHeartbeat: {
    route: "postHeartbeat",
    mediaType: "application/json",
    invoke: (bag) =>
      postHeartbeat(config, {
        aiInputTokens: bag.__body?.["ai_input_tokens"],
        aiLineChanges: bag.__body?.["ai_line_changes"],
        aiOutputTokens: bag.__body?.["ai_output_tokens"],
        aiPromptLength: bag.__body?.["ai_prompt_length"],
        aiSession: bag.__body?.["ai_session"],
        branch: bag.__body?.["branch"],
        category: bag.__body?.["category"],
        createdAt: bag.__body?.["created_at"],
        cursorpos: bag.__body?.["cursorpos"],
        editor: bag.__body?.["editor"],
        entity: bag.__body?.["entity"],
        humanLineChanges: bag.__body?.["human_line_changes"],
        isWrite: bag.__body?.["is_write"],
        language: bag.__body?.["language"],
        lineAdditions: bag.__body?.["line_additions"],
        lineDeletions: bag.__body?.["line_deletions"],
        lineno: bag.__body?.["lineno"],
        lines: bag.__body?.["lines"],
        machine: bag.__body?.["machine"],
        operatingSystem: bag.__body?.["operating_system"],
        project: bag.__body?.["project"],
        projectRootCount: bag.__body?.["project_root_count"],
        time: bag.__body?.["time"],
        ["type"]: bag.__body?.["type"],
        userAgent: bag.__body?.["user_agent"],
      }),
  },
  postHeartbeat5: {
    route: "postHeartbeat5",
    mediaType: "application/json",
    invoke: (bag) => postHeartbeat5(config, bag.__body),
  },
  postHeartbeat4: {
    route: "postHeartbeat4",
    mediaType: "application/json",
    invoke: (bag) =>
      postHeartbeat4(config, {
        aiInputTokens: bag.__body?.["ai_input_tokens"],
        aiLineChanges: bag.__body?.["ai_line_changes"],
        aiOutputTokens: bag.__body?.["ai_output_tokens"],
        aiPromptLength: bag.__body?.["ai_prompt_length"],
        aiSession: bag.__body?.["ai_session"],
        branch: bag.__body?.["branch"],
        category: bag.__body?.["category"],
        createdAt: bag.__body?.["created_at"],
        cursorpos: bag.__body?.["cursorpos"],
        editor: bag.__body?.["editor"],
        entity: bag.__body?.["entity"],
        humanLineChanges: bag.__body?.["human_line_changes"],
        isWrite: bag.__body?.["is_write"],
        language: bag.__body?.["language"],
        lineAdditions: bag.__body?.["line_additions"],
        lineDeletions: bag.__body?.["line_deletions"],
        lineno: bag.__body?.["lineno"],
        lines: bag.__body?.["lines"],
        machine: bag.__body?.["machine"],
        operatingSystem: bag.__body?.["operating_system"],
        project: bag.__body?.["project"],
        projectRootCount: bag.__body?.["project_root_count"],
        time: bag.__body?.["time"],
        ["type"]: bag.__body?.["type"],
        userAgent: bag.__body?.["user_agent"],
        user: bag["user"],
      }),
  },
  postHeartbeat8: {
    route: "postHeartbeat8",
    mediaType: "application/json",
    invoke: (bag) => postHeartbeat8(config, { body: bag.__body, user: bag["user"] }),
  },
  postHeartbeat2: {
    route: "postHeartbeat2",
    mediaType: "application/json",
    invoke: (bag) =>
      postHeartbeat2(config, {
        aiInputTokens: bag.__body?.["ai_input_tokens"],
        aiLineChanges: bag.__body?.["ai_line_changes"],
        aiOutputTokens: bag.__body?.["ai_output_tokens"],
        aiPromptLength: bag.__body?.["ai_prompt_length"],
        aiSession: bag.__body?.["ai_session"],
        branch: bag.__body?.["branch"],
        category: bag.__body?.["category"],
        createdAt: bag.__body?.["created_at"],
        cursorpos: bag.__body?.["cursorpos"],
        editor: bag.__body?.["editor"],
        entity: bag.__body?.["entity"],
        humanLineChanges: bag.__body?.["human_line_changes"],
        isWrite: bag.__body?.["is_write"],
        language: bag.__body?.["language"],
        lineAdditions: bag.__body?.["line_additions"],
        lineDeletions: bag.__body?.["line_deletions"],
        lineno: bag.__body?.["lineno"],
        lines: bag.__body?.["lines"],
        machine: bag.__body?.["machine"],
        operatingSystem: bag.__body?.["operating_system"],
        project: bag.__body?.["project"],
        projectRootCount: bag.__body?.["project_root_count"],
        time: bag.__body?.["time"],
        ["type"]: bag.__body?.["type"],
        userAgent: bag.__body?.["user_agent"],
        user: bag["user"],
      }),
  },
  postHeartbeat6: {
    route: "postHeartbeat6",
    mediaType: "application/json",
    invoke: (bag) => postHeartbeat6(config, { body: bag.__body, user: bag["user"] }),
  },
};

test("heartbeat methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
