// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  getWakatimeLeaders,
  getWakatimeUser,
  getAllTime,
  getWakatimeProjects,
  getWakatimeProject,
  getWakatimesTats,
  getWakatimeSummaries,
  getWakatimeUseragents,
  statusbar,
} from "../../dist/methods/wakatime.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getWakatimeLeaders: {
    route: "getWakatimeLeaders",
    mediaType: null,
    invoke: () => getWakatimeLeaders(config, {}),
  },
  getWakatimeUser: {
    route: "getWakatimeUser",
    mediaType: null,
    invoke: (bag) => getWakatimeUser(config, { user: bag["user"] }),
  },
  getAllTime: {
    route: "getAllTime",
    mediaType: null,
    invoke: (bag) => getAllTime(config, { user: bag["user"] }),
  },
  getWakatimeProjects: {
    route: "getWakatimeProjects",
    mediaType: null,
    invoke: (bag) => getWakatimeProjects(config, { user: bag["user"], q: bag["q"] }),
  },
  getWakatimeProject: {
    route: "getWakatimeProject",
    mediaType: null,
    invoke: (bag) => getWakatimeProject(config, { user: bag["user"], id: bag["id"] }),
  },
  getWakatimesTats: {
    route: "getWakatimesTats",
    mediaType: null,
    invoke: (bag) =>
      getWakatimesTats(config, {
        user: bag["user"],
        range: bag["range"],
        project: bag["project"],
        language: bag["language"],
        editor: bag["editor"],
        operatingSystem: bag["operating_system"],
        machine: bag["machine"],
        label: bag["label"],
      }),
  },
  getWakatimeSummaries: {
    route: "getWakatimeSummaries",
    mediaType: null,
    invoke: (bag) =>
      getWakatimeSummaries(config, {
        user: bag["user"],
        range: bag["range"],
        start: bag["start"],
        end: bag["end"],
        project: bag["project"],
        language: bag["language"],
        editor: bag["editor"],
        operatingSystem: bag["operating_system"],
        machine: bag["machine"],
        label: bag["label"],
      }),
  },
  getWakatimeUseragents: {
    route: "getWakatimeUseragents",
    mediaType: null,
    invoke: (bag) => getWakatimeUseragents(config, { user: bag["user"] }),
  },
  statusbar: {
    route: "statusbar",
    mediaType: null,
    invoke: (bag) => statusbar(config, { user: bag["user"] }),
  },
};

test("wakatime methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
