// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { spawn } from "node:child_process";
import { readFileSync } from "node:fs";

const ROUTES = JSON.parse(readFileSync(new URL("../mock-routes.json", import.meta.url), "utf8"));

/**
 * Starts the bundled mock server on an ephemeral port and resolves once it is
 * listening. One server serves every namespace's tests.
 */
export const startMockServer = async () => {
  if (process.env.SDK_METHOD_TEST_BASE_URL) {
    return {
      baseUrl: process.env.SDK_METHOD_TEST_BASE_URL,
      stop: () => {},
    };
  }
  const server = spawn(
    process.execPath,
    [new URL("../mock-server.mjs", import.meta.url).pathname, "--port", "0"],
    { stdio: ["ignore", "pipe", "pipe"] },
  );
  const port = await new Promise((resolve, reject) => {
    let buffered = "";
    const timer = setTimeout(
      () => reject(new Error("mock server did not report a port in 10s")),
      10_000,
    );
    // The server announces itself as one JSON line: {"port":N,"routes":…}.
    server.stdout.on("data", (chunk) => {
      buffered += chunk.toString();
      for (const line of buffered.split("\n")) {
        if (!line.trim()) continue;
        try {
          const announcement = JSON.parse(line);
          if (announcement.port) {
            clearTimeout(timer);
            resolve(Number(announcement.port));
            return;
          }
        } catch {
          // Partial line; wait for the rest.
        }
      }
    });
    server.on("error", reject);
  });
  return {
    baseUrl: `http://127.0.0.1:${port}`,
    stop: () => server.kill("SIGKILL"),
  };
};

/** Normalized keys of the request body, i.e. the fields the mock may echo. */
export const echoedKeys = (route) => {
  const normalize = (key) => key.replace(/[^a-z0-9]/gi, "").toLowerCase();
  // The mock echoes PATH parameters as well as request-body fields, so a
  // response carrying the id actually requested legitimately differs from the
  // static example's id.
  const echoed = new Set(
    (route.pathParameters ?? []).map((parameter) => normalize(parameter.wireName)),
  );
  const body = (route.requestModes ?? []).find((mode) => mode.example !== undefined);
  const example = body?.example;
  if (!example || typeof example !== "object" || Array.isArray(example)) {
    return echoed;
  }
  for (const key of Object.keys(example)) echoed.add(normalize(key));
  return echoed;
};

/** The route description the mock server serves for an operation. */
export const routeFor = (operationId) =>
  ROUTES.find((route) => route.operationId === operationId) ?? null;

/**
 * Values for one operation's parameters, taken from the same examples the mock
 * server answers with, keyed by the parameter's WIRE name. The generated call
 * map translates those to idiomatic argument names.
 */
export const argumentsFor = (route, mediaType = null) => {
  const values = {};
  for (const parameter of route.pathParameters ?? []) {
    values[parameter.wireName] = parameter.example ?? "sample";
  }
  for (const parameter of route.queryParameters ?? []) {
    if (parameter.example !== undefined) values[parameter.wireName] = parameter.example;
  }
  for (const parameter of [...(route.headerParameters ?? []), ...(route.cookieParameters ?? [])]) {
    if (parameter.example !== undefined) values[parameter.wireName] = parameter.example;
  }
  const modes = (route.requestModes ?? []).filter((mode) => mode.example !== undefined);
  // Prefer the mode this method actually encodes: one operation's modes can
  // name the same data differently (createImageEdit takes JSON images or
  // multipart image), and feeding the wrong one leaves the argument undefined.
  const body = modes.find((mode) => mediaType !== null && mode.mediaType === mediaType) ?? modes[0];
  if (body) values.__body = body.example;
  return values;
};

/**
 * Every 2xx response the route declares with a body. An operation can declare
 * several (200 AND 201, say); which one the mock answers with is its own
 * decision, so the assertion accepts a match against any of them rather than
 * betting on one.
 */
export const expectedResponses = (route) =>
  (route.responseModes ?? []).filter(
    (mode) =>
      String(mode.statusCode).startsWith("2") &&
      mode.example !== undefined &&
      mode.decoderKind !== "empty",
  );

/**
 * Every field the expected example declares is present in the response with the
 * same value. A subset check, deliberately: a decoded model may carry defaults
 * the example omits, and that is not a failure.
 */
// A binary response decodes to a byte container, never to the example's shape.
// The fetch engine yields a Blob and the axios engine a Uint8Array; either way
// the contract worth asserting is that the declared bytes arrived.
export const matchesBytes = (actual, mode) => {
  if (mode.decoderKind !== "bytes") return false;
  const expectedLength =
    typeof mode.bodyBase64 === "string" ? Buffer.from(mode.bodyBase64, "base64").byteLength : 0;
  let actualLength = -1;
  if (actual instanceof Uint8Array || actual instanceof ArrayBuffer)
    actualLength = actual.byteLength;
  else if (typeof Blob !== "undefined" && actual instanceof Blob) actualLength = actual.size;
  return actualLength === expectedLength;
};

export const matchesExpected = (actual, expected, echoed = new Set()) => {
  if (expected === null || typeof expected !== "object") {
    return Object.is(actual, expected);
  }
  if (Array.isArray(expected)) {
    return (
      Array.isArray(actual) &&
      actual.length === expected.length &&
      expected.every((item, index) => matchesExpected(actual[index], item, echoed))
    );
  }
  if (actual === null || typeof actual !== "object") return false;
  // The SDK decodes wire names into idiomatic ones (`node_id` → `nodeId`), so
  // keys are matched on their letters and digits alone.
  const normalize = (key) => key.replace(/[^a-z0-9]/gi, "").toLowerCase();
  const actualByKey = new Map(
    Object.entries(actual).map(([key, value]) => [normalize(key), value]),
  );
  return Object.entries(expected).every(([key, value]) => {
    const found = Object.hasOwn(actual, key) ? actual[key] : actualByKey.get(normalize(key));
    // The mock echoes request fields back into its response, so a field we
    // SENT legitimately differs from the static example: require that it came
    // back at all, not that it matches the example's value.
    if (echoed.has(normalize(key))) return found !== undefined;
    return matchesExpected(found, value, echoed);
  });
};

// An auto-paginating method yields the page's ITEMS, while the declared 2xx
// example is the page ENVELOPE. Compare what was yielded against the envelope's
// results array instead of against the envelope itself.
export const matchesPagedExpected = (actual, expected, echoed = new Set()) => {
  if (expected === null || typeof expected !== "object") return false;
  const results = Object.values(expected).find((value) => Array.isArray(value));
  if (!Array.isArray(results)) return false;
  const items = Array.isArray(actual) ? actual : [actual];
  // An envelope stating an empty page is matched by yielding nothing. Reading
  // that as a failure would mark every endpoint whose authored example carries
  // no rows as broken.
  if (results.length === 0) return items.length === 0;
  if (items.length === 0) return false;
  return items.every((item) =>
    results.some((candidate) => matchesExpected(item, candidate, echoed)),
  );
};
