// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { formatQueryValue } from "./client-utils";
import { wireSchemas } from "./wire";

export interface SdkResponse<T> {
  data: T;
  statusCode: number;
  headers: Readonly<Record<string, string>>;
  requestId: string | null;
  latencyMs: number;
  attempt: number;
}

// ── Wire-format remapping ───────────────────────────────────────────────────
// Model properties are exposed under idiomatic camelCase names, but the API
// speaks the exact field names from the spec (e.g. `display-name`). These
// helpers translate payloads across that boundary — `toWire` before a request,
// `fromWire` after a response — driven by the per-model field maps in `./wire`.

/**
 * Runtime descriptor for one model field. `wire` is the JSON key as it appears
 * on the wire; `type` names a nested model whose own schema drives recursion;
 * `fields` carries the map of an inline object property, which has no model name
 * to point at. Arrays are detected at runtime, so a field holding `Type[]` still
 * uses `{ type: "Type" }`.
 */
export interface WireField {
  wire: string;
  type?: string;
  fields?: WireSchema;
}
export type WireSchema = Record<string, WireField>;

/**
 * Translates a value between the idiomatic SDK shape and the wire shape.
 * `toWire` renames SDK keys → wire keys; `fromWire` renames wire keys → SDK
 * keys. Recurses into nested models, inline object properties and arrays; values
 * whose type has no registered schema (primitives, unions, free-form objects) pass
 * through untouched, as do models whose keys already match on both sides. Keys a
 * map does not list (additionalProperties, union or free-form allOf members) are
 * copied verbatim, so remapping never drops data.
 */
function remapShape(value: unknown, schema: WireSchema, direction: "toWire" | "fromWire"): unknown {
  if (value == null) return value;
  if (Array.isArray(value)) return value.map((item) => remapShape(item, schema, direction));
  if (typeof value !== "object") return value;

  const source = value as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  const hasOwn = (key: string): boolean => Object.prototype.hasOwnProperty.call(source, key);
  const setOwn = (key: string, fieldValue: unknown): void => {
    Object.defineProperty(out, key, {
      configurable: true,
      enumerable: true,
      value: fieldValue,
      writable: true,
    });
  };
  const mapped = new Set<string>();
  for (const [sdkKey, field] of Object.entries(schema)) {
    mapped.add(field.wire);
    if (direction === "toWire") mapped.add(sdkKey);
  }
  for (const [key, fieldValue] of Object.entries(source)) {
    if (!mapped.has(key)) setOwn(key, fieldValue);
  }
  for (const [sdkKey, field] of Object.entries(schema)) {
    const nested = (child: unknown): unknown =>
      field.type
        ? remapWire(child, field.type, direction)
        : field.fields
          ? remapShape(child, field.fields, direction)
          : child;
    if (direction === "toWire") {
      // Accept values keyed by the idiomatic name or already by the wire name,
      // so callers may pass model-shaped or wire-shaped objects.
      const from = hasOwn(sdkKey) ? sdkKey : field.wire;
      if (!hasOwn(from)) continue;
      setOwn(field.wire, nested(source[from]));
    } else {
      if (!hasOwn(field.wire)) continue;
      setOwn(sdkKey, nested(source[field.wire]));
    }
  }
  return out;
}

function remapWire(value: unknown, typeName: string, direction: "toWire" | "fromWire"): unknown {
  const schema = wireSchemas[typeName];
  if (value == null || !schema) return value;
  return remapShape(value, schema, direction);
}

/** Renames a request payload's keys from idiomatic SDK names to wire names. */
export function toWire(value: unknown, typeName: string): unknown {
  return remapWire(value, typeName, "toWire");
}

/** Renames a response payload's keys from wire names to idiomatic SDK names. */
export function fromWire(value: unknown, typeName: string): unknown {
  return remapWire(value, typeName, "fromWire");
}

/**
 * A single in-flight HTTP attempt as seen by middleware. Middleware may mutate
 * `headers`, replace `body`, or short-circuit by returning a response without
 * calling `next`. `attempt` increments on each retry; `meta` is a free-form
 * scratch space middleware can use to coordinate across the chain.
 */
export interface SdkRequest {
  method: string;
  url: string;
  headers: Record<string, string>;
  body: BodyInit | undefined;
  operationId: string;
  attempt: number;
  signal: AbortSignal;
  responseDecoder: "json" | "text" | "bytes" | "empty";
  meta: Record<string, unknown>;
}

export type SdkNext = (request: SdkRequest) => Promise<SdkResponse<unknown>>;

/**
 * User-supplied request interceptor. Runs once per HTTP attempt (so retries
 * pass through it N times). Compose patterns like logging, tracing, caching,
 * custom auth, or response transforms without forking the generator.
 *
 * @example
 *   configureClient({
 *     middleware: [
 *       async (req, next) => {
 *         const res = await next(req);
 *         console.log(`${req.method} ${req.url} → ${res.statusCode}`);
 *         return res;
 *       },
 *     ],
 *   });
 */
export type Middleware = (request: SdkRequest, next: SdkNext) => Promise<SdkResponse<unknown>>;

export interface RetryConfig {
  maxAttempts: number;
  retryOn: readonly number[];
  backoffMs: number;
  maxBackoffMs: number;
}

export interface IdempotencyConfig {
  /** Defaults to `true`. Set to `false` to disable client-side key generation. */
  enabled?: boolean;
  /** Header name. Defaults to `Idempotency-Key` (Stripe convention). */
  headerName?: string;
  /** HTTP methods that should receive a key. Defaults to `["POST", "PATCH"]`. */
  methods?: readonly string[];
}

export interface ClientAuth {
  apiKeyAuth?: string;

  /** Extra headers attached to every request (escape hatch). */
  headers?: Record<string, string>;
}

/** A breadcrumb: one event in the trail leading up to an error. */
export interface Breadcrumb {
  timestamp?: string;
  type?: string;
  category?: string;
  level?: "debug" | "info" | "warning" | "error";
  message?: string;
  data?: Record<string, unknown>;
}

export interface LoggingConfig {
  enabled?: boolean;
  endpoint?: string;
  apiKey?: string;
  /**
   * GDPR consent gate. When false (the default), personal data — the user,
   * device/page context, and breadcrumbs — is NOT sent; only the error itself
   * and the operation are reported. Call `setLoggingConsent(true)` once the end
   * user has approved tracking.
   */
  consent?: boolean;
  /** Deployment environment forwarded with every logged event (e.g. "production"). */
  environment?: string;
  /** Release/version identifier forwarded with every logged event. */
  release?: string;
  /** User metadata attached to logged events (e.g. `{ id, email }`). Consent-gated. */
  user?: Record<string, unknown>;
  /** Arbitrary tags attached to logged events (e.g. `{ region: "eu" }`). */
  tags?: Record<string, unknown>;
  /** Max breadcrumbs retained in the rolling buffer (default 30). */
  maxBreadcrumbs?: number;
  /** Redact common credentials and direct identifiers before telemetry is sent (default true). */
  filterPii?: boolean;
}

export interface ClientConfig {
  baseUrl?: string;
  auth?: ClientAuth;
  retry?: Partial<RetryConfig>;
  idempotency?: IdempotencyConfig;
  timeoutMs?: number;
  logging?: LoggingConfig;
  onResponse?: (response: SdkResponse<unknown>) => void;
  /**
   * User middleware chain. Each middleware wraps a single HTTP attempt — they
   * see every retry. Outermost-first ordering: `[a, b]` runs `a` → `b` → core
   * transport, then unwinds.
   */
  middleware?: readonly Middleware[];
}

export interface SdkRequestOptions {
  method: string;
  path: string;
  query?: Record<string, unknown>;
  body?: unknown;
  /** Per-request headers, merged over the auth and operation headers. */
  headers?: Record<string, string>;
  contentType?: string;
  operationId: string;
  /** Canonical response mode selected from the shared operation wire model. */
  responseDecoder?: "json" | "text" | "bytes" | "empty";
  config?: ClientConfig;
  /**
   * Per-request override. Pass a string to use a specific key, `null` to
   * suppress the auto-generated key for this call. `undefined` (the default)
   * uses the config's idempotency policy.
   */
  idempotencyKey?: string | null;
  /**
   * Per-call retry override. The generator emits this for operations the SDK
   * owner gave method-specific reliability settings; it layers over the config's
   * retry policy (and the client defaults) for this call only.
   */
  retry?: Partial<RetryConfig>;
  /** Per-call timeout override (ms), layered over config / client default. */
  timeoutMs?: number;
  /**
   * Caller cancellation. Aborting this signal ends the call with
   * `SdkCancelledError` — before dispatch, in flight, or while waiting between
   * retries — and the SDK does not retry a cancelled call. The SDK's own
   * timeout deadline stays separate and still raises `SdkTimeoutError`.
   */
  signal?: AbortSignal;
}

/**
 * Per-call options every generated operation accepts as its last argument. Each
 * one applies to that call only, over the operation's own settings and the
 * client config.
 */
export type RequestOptions = Pick<
  SdkRequestOptions,
  "headers" | "idempotencyKey" | "retry" | "timeoutMs" | "signal"
>;

export interface MultipartPart {
  data: Blob | Uint8Array | string;
  contentType: string;
  filename?: string;
}

export function multipartJson(
  value: unknown,
  contentType = "application/json",
): MultipartPart | undefined {
  if (value === undefined) return undefined;
  return { data: JSON.stringify(value), contentType };
}

export function parameterWireValue(value: unknown, format?: "date" | "date-time"): string {
  if (!(value instanceof Date)) return String(value);
  const timestamp = value.toISOString();
  return format === "date" ? timestamp.slice(0, 10) : timestamp;
}

/** Percent-encodes exactly one path component exactly once. */
export function encodePathSegment(value: unknown, format?: "date" | "date-time"): string {
  return encodeURIComponent(parameterWireValue(value, format));
}

export function queryValue(
  value: unknown,
  style = "form",
  explode = true,
  format?: "date" | "date-time",
): unknown {
  if (value === undefined || value === null) return undefined;
  if (!Array.isArray(value)) return parameterWireValue(value, format);
  const encoded = value.map((item) => parameterWireValue(item, format));
  return style === "form" && explode ? encoded : encoded.join(",");
}

export function serializeHeaders(values: Record<string, unknown>): Record<string, string> {
  const headers: Record<string, string> = {};
  for (const [name, value] of Object.entries(values)) {
    if (value === undefined || value === null) continue;
    headers[name] = Array.isArray(value)
      ? value.map(formatQueryValue).join(",")
      : formatQueryValue(value);
  }
  return headers;
}

/**
 * The request context passed to an operation's `beforeRequest` hook. Read
 * `params`, or mutate `query` / `body` / `headers`, then return it — the returned
 * context is what the SDK sends. (SDK Studio "custom code".)
 *
 * Generic over the body + query shapes so a hook can refine them (the return type
 * is editable via the type parameters) while the base shape stays strict. The
 * defaults are open records, so a NEW `query`/`body` field the hook adds still
 * type-checks and is passed straight through to the request.
 */
export interface RequestContext<TBody = Record<string, unknown>, TQuery = Record<string, unknown>> {
  params: Record<string, unknown>;
  query: TQuery;
  body: TBody;
  headers: Record<string, string>;
}
