// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

export function formatQueryValue(value: unknown): string {
  if (value instanceof Date) return value.toISOString();
  return String(value);
}
