// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { SdkAuthError } from "./errors";
import { formatQueryValue } from "./client-utils";
import type {
  ClientAuth,
  ClientConfig,
  Middleware,
  MultipartPart,
  RetryConfig,
  SdkNext,
  SdkRequest,
  SdkResponse,
} from "./client-types";
/**
 * Security alternatives per operation, keyed by the identifier the generated
 * request layer reports. Each alternative is the set of scheme names that
 * satisfies it; an empty alternative means the specification allows the call
 * without credentials.
 */
const OPERATION_SECURITY: Readonly<Record<string, readonly (readonly string[])[]>> = {
  getWakatimeLeaders: [["ApiKeyAuth"]],

  getWakatimeUser: [["ApiKeyAuth"]],

  getAllTime: [["ApiKeyAuth"]],

  getHeartbeats: [["ApiKeyAuth"]],

  postHeartbeat3: [["ApiKeyAuth"]],

  postHeartbeat7: [["ApiKeyAuth"]],

  getWakatimeProjects: [["ApiKeyAuth"]],

  getWakatimeProject: [["ApiKeyAuth"]],

  getWakatimesTats: [["ApiKeyAuth"]],

  getWakatimeSummaries: [["ApiKeyAuth"]],

  getWakatimeUseragents: [["ApiKeyAuth"]],

  postHeartbeat: [["ApiKeyAuth"]],

  postHeartbeat5: [["ApiKeyAuth"]],

  getSummary: [["ApiKeyAuth"]],

  postHeartbeat4: [["ApiKeyAuth"]],

  postHeartbeat8: [["ApiKeyAuth"]],

  statusbar: [["ApiKeyAuth"]],

  postHeartbeat2: [["ApiKeyAuth"]],

  postHeartbeat6: [["ApiKeyAuth"]],
};

/** Scheme names this package carries a credential field for. */
const SUPPORTED_SCHEMES: ReadonlySet<string> = new Set(["ApiKeyAuth"]);

/** True when the caller configured the credential this scheme reads. */
export function hasCredential(auth: ClientAuth, scheme: string): boolean {
  switch (scheme) {
    case "ApiKeyAuth":
      return Boolean(auth.apiKeyAuth);
    default:
      return false;
  }
}

/**
 * Chooses the security alternative this call will satisfy.
 *
 * Returns the scheme names to apply, or null when the operation declares no
 * security. An operation whose every alternative demands a scheme this package
 * cannot supply is refused here rather than sent with the wrong credential or
 * with none at all.
 *
 * A package that carries credentials for several schemes usually has only some
 * of them configured, so a configured alternative is preferred over the first
 * supported one; with none configured the first supported alternative still
 * applies, and its own scheme raises the diagnostic it owes the caller.
 */
export function selectAuthAlternative(
  operationId: string,
  auth: ClientAuth,
): readonly string[] | null {
  const alternatives = OPERATION_SECURITY[operationId];
  if (!alternatives || alternatives.length === 0) return null;
  // An empty alternative is the specification saying authentication is optional.
  if (alternatives.some((alternative) => alternative.length === 0)) return null;
  const supported = alternatives.filter((alternative) =>
    alternative.every((scheme) => SUPPORTED_SCHEMES.has(scheme)),
  );

  const configured = supported.find((alternative) =>
    alternative.every((scheme) => hasCredential(auth, scheme)),
  );
  if (configured) return configured;

  if (supported.length > 0) return supported[0];
  const required = [...new Set(alternatives.flat())];
  throw new SdkAuthError(operationId, required);
}
const IDEMPOTENT_METHODS = new Set(["GET", "HEAD", "PUT", "DELETE", "OPTIONS"]);
// POSTs/PATCHes are not safe to blindly retry on 5xx; only the explicit
// "back off and try again" statuses are safe across all methods.
const ALWAYS_RETRYABLE_STATUSES = new Set([429, 503]);
const REQUEST_ID_HEADERS = ["x-request-id", "openai-request-id", "x-amzn-requestid"];

/**
 * Composes a middleware chain into a single dispatch function. The first
 * middleware in `stack` is the outermost; `terminal` is the innermost call
 * (the actual HTTP transport).
 */
export function composeMiddleware(stack: readonly Middleware[], terminal: SdkNext): SdkNext {
  if (stack.length === 0) return terminal;
  return stack.reduceRight<SdkNext>((next, mw) => (req) => mw(req, next), terminal);
}

/**
 * Innermost dispatch: performs the actual `fetch` and assembles an
 * `SdkResponse`. Non-2xx responses are returned as-is so middleware can
 * inspect or transform them; only network/abort errors throw.
 */
export async function coreTransport(request: SdkRequest): Promise<SdkResponse<unknown>> {
  const startedAt = Date.now();
  const response = await fetch(request.url, {
    method: request.method,
    headers: request.headers,
    body: request.body,
    signal: request.signal,
  });
  const respHeaders = collectHeaders(response);
  const requestId = findRequestId(respHeaders);
  const data = await parseResponseBody(response, response.ok ? request.responseDecoder : "auto");
  return {
    data,
    statusCode: response.status,
    headers: respHeaders,
    requestId,
    latencyMs: Date.now() - startedAt,
    attempt: request.attempt,
  };
}

/** True for a request cancelled by the timeout controller. */
export function isAbortError(error: unknown): boolean {
  return error instanceof Error && error.name === "AbortError";
}

export function generateIdempotencyKey(): string {
  // crypto.randomUUID is available in Node 19+, modern browsers, Deno, Bun,
  // and Cloudflare Workers. Fall back to a Math.random UUID v4 for older
  // runtimes — sufficient for client-side idempotency keys (server uniqueness
  // is the actual guarantee).
  const g = globalThis as { crypto?: { randomUUID?: () => string } };
  if (g.crypto?.randomUUID) return g.crypto.randomUUID();
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

export function randomHex(bytes: number): string {
  const g = globalThis as { crypto?: { getRandomValues?: (a: Uint8Array) => Uint8Array } };
  const arr = new Uint8Array(bytes);
  if (g.crypto?.getRandomValues) {
    g.crypto.getRandomValues(arr);
  } else {
    for (let i = 0; i < bytes; i += 1) arr[i] = (Math.random() * 256) | 0;
  }
  return Array.from(arr, (b) => b.toString(16).padStart(2, "0")).join("");
}

// W3C trace-context ids: a 16-byte trace id + an 8-byte span id (lowercase hex).
// The trace id correlates this request's client error with the server error the
// backend's Octri package reports for the same request.
export function generateTraceId(): string {
  return randomHex(16);
}
export function generateSpanId(): string {
  return randomHex(8);
}

export function mergeConfig(base: ClientConfig, overrides: ClientConfig): ClientConfig {
  // `middleware` is replaced wholesale, not concatenated — concatenation would
  // make it impossible to remove a middleware once added. Callers wanting to
  // append should spread: `middleware: [...getClientConfig().middleware ?? [], myMw]`.
  return {
    ...base,
    ...overrides,
    auth: { ...base.auth, ...overrides.auth },
    retry: { ...base.retry, ...overrides.retry },
    idempotency: { ...base.idempotency, ...overrides.idempotency },
    logging: { ...base.logging, ...overrides.logging },
  };
}

export function buildUrl(
  baseUrl: string,
  path: string,
  query: Record<string, unknown> | undefined,
  extraQuery: Record<string, string>,
): string {
  const params = new URLSearchParams();
  if (query) {
    for (const [key, value] of Object.entries(query)) {
      if (value === undefined || value === null) continue;
      if (Array.isArray(value)) {
        for (const item of value) {
          if (item === undefined || item === null) continue;
          params.append(key, formatQueryValue(item));
        }
      } else if (typeof value === "object") {
        params.append(key, JSON.stringify(value));
      } else {
        params.append(key, formatQueryValue(value));
      }
    }
  }
  for (const [key, value] of Object.entries(extraQuery)) {
    params.set(key, value);
  }
  // Absolute URLs (used by url-style pagination follow links) bypass baseUrl.
  const isAbsolute = /^https?:\/\//i.test(path);
  // The join is a seam between two values the SDK does not own: a base URL that may end in a
  // slash and a path that begins with one. Concatenating them produced `/api//things`, which
  // some gateways answer with a 404 and some normalize, so the seam is normalized here.
  const root = isAbsolute ? path : `${baseUrl.replace(/\/+$/, "")}${path}`;
  const qs = params.toString();
  if (!qs) return root;
  return root.includes("?") ? `${root}&${qs}` : `${root}?${qs}`;
}

/**
 * Reads the configured auth and applies each declared scheme. Auth fields the
 * caller didn't populate are silently skipped — callers only need to set the
 * schemes they actually use.
 */
export async function applyAuth(
  config: ClientConfig,
  headers: Record<string, string>,
  _query: Record<string, string>,
  operationId?: string,
): Promise<void> {
  // Refusal comes first: an operation this package cannot satisfy must fail even
  // when the caller configured no credentials at all. Only the schemes of the
  // chosen alternative are then applied, so a credential configured for one
  // operation never travels on another.
  const _selected =
    operationId === undefined ? null : selectAuthAlternative(operationId, config.auth ?? {});
  const _applies = (scheme: string) => (_selected === null ? false : _selected.includes(scheme));

  // Not an early return: an operation whose chosen alternative requires a
  // credential must raise its scheme's diagnostic when none is configured,
  // rather than going out unauthenticated. Appliers skip absent fields.
  const auth = config.auth ?? {};

  if (_applies("ApiKeyAuth") && auth.apiKeyAuth) headers["Authorization"] = auth.apiKeyAuth;
}

export function serializeBody(body: unknown, contentType: string): BodyInit | undefined {
  if (body === undefined) return undefined;
  // One JSON record per line; a JSON text sequence also starts each with RS.
  if (
    /^application\/(?:x-ndjson|ndjson|jsonl|json-lines|x-jsonlines|json-seq)(?:\s*;|$)/i.test(
      contentType,
    )
  ) {
    const separator = /^application\/json-seq/i.test(contentType) ? "\x1e" : "";
    return (Array.isArray(body) ? body : [body])
      .map((record) => `${separator}${JSON.stringify(record)}\n`)
      .join("");
  }
  if (contentType.includes("json")) return JSON.stringify(body);
  // application/x-www-form-urlencoded: encode the field map here rather than
  // leaving it to the transport. Only an already-encoded string is equivalent
  // across every engine — handing a plain object to the runtime yields
  // "[object Object]" on one engine and a form-encoded body on another.
  if (
    contentType.startsWith("application/x-www-form-urlencoded") &&
    body !== null &&
    typeof body === "object" &&
    !(body instanceof URLSearchParams)
  ) {
    const params = new URLSearchParams();
    const append = (key: string, value: unknown): void => {
      if (value === undefined) return;
      if (Array.isArray(value)) {
        for (const item of value) append(key, item);
        return;
      }
      if (value !== null && typeof value === "object") {
        params.append(key, JSON.stringify(value));
        return;
      }
      params.append(key, value === null ? "null" : String(value));
    };
    for (const [key, value] of Object.entries(body as Record<string, unknown>)) {
      append(key, value);
    }
    return params.toString();
  }
  // multipart/form-data: build a FormData from the field map. Blob/File values
  // become file parts; everything else is appended as a string. The runtime
  // sets the Content-Type (with boundary), so the header isn't set manually.
  if (
    contentType.startsWith("multipart/form-data") &&
    body !== null &&
    typeof body === "object" &&
    !(body instanceof FormData)
  ) {
    const form = new FormData();
    const append = (key: string, value: unknown): void => {
      if (value === undefined) return;
      if (Array.isArray(value)) {
        for (const item of value) append(key, item);
        return;
      }
      if (isMultipartPart(value)) {
        let part: Blob;
        if (value.data instanceof Blob) {
          part = value.data;
        } else if (value.data instanceof Uint8Array) {
          // Copy into an ArrayBuffer-backed view. A caller may provide a
          // Uint8Array<ArrayBufferLike> whose buffer is a SharedArrayBuffer,
          // which is intentionally not accepted as a BlobPart by lib.dom.
          const bytes = new Uint8Array(value.data.byteLength);
          bytes.set(value.data);
          part = new Blob([bytes.buffer], { type: value.contentType });
        } else {
          part = new Blob([value.data], { type: value.contentType });
        }
        form.append(key, part, value.filename);
        return;
      }
      if (value instanceof Blob) {
        const filename =
          typeof File !== "undefined" && value instanceof File ? value.name : undefined;
        form.append(key, value, filename);
        return;
      }
      if (value !== null && typeof value === "object") {
        form.append(key, JSON.stringify(value));
        return;
      }
      form.append(key, value === null ? "null" : String(value));
    };
    for (const [key, value] of Object.entries(body as Record<string, unknown>)) {
      append(key, value);
    }
    return form;
  }
  return body as BodyInit;
}

export function isMultipartPart(value: unknown): value is MultipartPart {
  return (
    value !== null &&
    typeof value === "object" &&
    "data" in value &&
    "contentType" in value &&
    typeof (value as { contentType?: unknown }).contentType === "string"
  );
}

export function collectHeaders(response: Response): Record<string, string> {
  const out: Record<string, string> = {};
  response.headers.forEach((value, key) => {
    out[key.toLowerCase()] = value;
  });
  return out;
}

export function findRequestId(headers: Record<string, string>): string | null {
  for (const name of REQUEST_ID_HEADERS) {
    if (headers[name]) return headers[name];
  }
  return null;
}

export function isJsonMediaType(contentType: string): boolean {
  const mediaType = contentType.split(";", 1)[0]?.trim().toLowerCase() ?? "";
  return mediaType === "application/json" || mediaType.endsWith("+json");
}

export function isResponseTextual(contentType: string): boolean {
  return (
    contentType.length === 0 || isJsonMediaType(contentType) || contentType.startsWith("text/")
  );
}

export function parseJsonIfValid(
  text: string,
): { parsed: true; value: unknown } | { parsed: false } {
  try {
    return { parsed: true, value: JSON.parse(text) };
  } catch {
    return { parsed: false };
  }
}

export async function parseResponseBody(
  response: Response,
  decoder: "auto" | "json" | "text" | "bytes" | "empty" = "auto",
): Promise<unknown> {
  if (decoder === "empty") return null;
  if (decoder === "text") return response.text();
  if (decoder === "bytes") return response.blob();
  const contentType = response.headers.get("Content-Type") ?? "";
  if (decoder === "json") {
    const text = await response.text();
    if (text.length === 0) {
      throw new SyntaxError("Expected a JSON response body but received zero bytes");
    }
    return JSON.parse(text);
  }
  if (response.status === 204 || response.status === 205) return null;
  if (isResponseTextual(contentType)) {
    const text = await response.text();
    if (text.length === 0) return null;
    const parsed = parseJsonIfValid(text);
    if (parsed.parsed) return parsed.value;
    return text;
  }
  return response.blob();
}

/**
 * Whether an attempt that produced no response may be repeated. A timeout or reset says
 * nothing about whether the server processed the request, so repeating is safe only for an
 * idempotent method, or when a key was sent for the service to deduplicate on.
 */
export function mayRepeatRequest(
  method: string,
  idempotencyKey: string | null | undefined,
): boolean {
  return IDEMPOTENT_METHODS.has(method) || Boolean(idempotencyKey);
}

export function shouldRetryStatus(
  method: string,
  status: number,
  retryOn: readonly number[],
): boolean {
  if (!retryOn.includes(status)) return false;
  if (IDEMPOTENT_METHODS.has(method)) return true;
  return ALWAYS_RETRYABLE_STATUSES.has(status);
}

export function computeBackoff(
  retry: RetryConfig,
  attempt: number,
  retryAfter: string | null,
): number {
  if (retryAfter) {
    const seconds = Number(retryAfter);
    if (!Number.isNaN(seconds) && seconds > 0) {
      return Math.min(seconds * 1000, retry.maxBackoffMs);
    }
    const date = Date.parse(retryAfter);
    if (!Number.isNaN(date)) {
      return Math.min(Math.max(date - Date.now(), 0), retry.maxBackoffMs);
    }
  }
  const exponential = retry.backoffMs * 2 ** (attempt - 1);
  const jitter = Math.random() * retry.backoffMs;
  return Math.min(exponential + jitter, retry.maxBackoffMs);
}
