// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  SdkCancelledError,
  SdkHttpError,
  SdkNetworkError,
  SdkStreamParseError,
  SdkTimeoutError,
} from "./errors";
import type {
  Breadcrumb,
  ClientConfig,
  IdempotencyConfig,
  LoggingConfig,
  RetryConfig,
  SdkRequest,
  SdkRequestOptions,
  SdkResponse,
} from "./client-types";
import {
  applyAuth,
  buildUrl,
  collectHeaders,
  composeMiddleware,
  computeBackoff,
  coreTransport,
  findRequestId,
  generateIdempotencyKey,
  generateSpanId,
  generateTraceId,
  isAbortError,
  mayRepeatRequest,
  mergeConfig,
  parseResponseBody,
  serializeBody,
  shouldRetryStatus,
} from "./client-transport";
export * from "./client-types";
const DEFAULT_RETRY: RetryConfig = {
  maxAttempts: 3,
  retryOn: [408, 425, 429, 500, 502, 503, 504],
  backoffMs: 500,
  maxBackoffMs: 8000,
};

const DEFAULT_IDEMPOTENCY: Required<IdempotencyConfig> = {
  enabled: true,
  headerName: "Idempotency-Key",
  methods: ["POST", "PATCH"],
};

// Baked monitoring telemetry. `enabled` is false at rest — the endpoint is
// pre-wired, but nothing is sent until the consumer opts in (see setLoggingConfig).
const DEFAULT_LOGGING: LoggingConfig = { enabled: false, filterPii: true };

const PII_KEYS = new Set([
  "authorization",
  "cookie",
  "set_cookie",
  "setcookie",
  "password",
  "passcode",
  "secret",
  "token",
  "api_key",
  "apikey",
  "access_token",
  "accesstoken",
  "refresh_token",
  "refreshtoken",
  "client_secret",
  "clientsecret",
  "email",
  "email_address",
  "emailaddress",
  "phone",
  "phone_number",
  "phonenumber",
  "address",
  "street_address",
  "streetaddress",
  "street",
  "city",
  "postal_code",
  "postalcode",
  "zip_code",
  "zipcode",
  "first_name",
  "firstname",
  "last_name",
  "lastname",
  "full_name",
  "fullname",
  "username",
  "user_name",
  "ip",
  "ip_address",
  "ipaddress",
  "user_agent",
  "useragent",
  "referrer",
  "url",
  "uri",
  "query",
  "latitude",
  "longitude",
  "ssn",
  "social_security_number",
  "socialsecuritynumber",
  "tax_id",
  "taxid",
  "national_id",
  "nationalid",
  "passport_number",
  "passportnumber",
  "date_of_birth",
  "dateofbirth",
  "birth_date",
  "birthdate",
  "headers",
  "body",
  "request_headers",
  "requestheaders",
  "request_body",
  "requestbody",
]);
// Word runs matched anywhere inside a key (`billingEmail`, `stripe_secret_key`).
const PII_SEGMENTS = [
  "_password_",
  "_passwd_",
  "_passphrase_",
  "_secret_",
  "_token_",
  "_api_key_",
  "_access_token_",
  "_refresh_token_",
  "_client_secret_",
  "_authorization_",
  "_cookie_",
  "_set_cookie_",
  "_credential_",
  "_private_key_",
  "_access_key_",
  "_session_id_",
  "_card_number_",
  "_credit_card_",
  "_cvv_",
  "_cvc_",
  "_email_",
  "_email_address_",
  "_phone_",
  "_phone_number_",
  "_address_",
  "_street_address_",
  "_postal_code_",
  "_zip_code_",
  "_first_name_",
  "_last_name_",
  "_full_name_",
  "_user_name_",
  "_user_agent_",
  "_ssn_",
  "_social_security_number_",
  "_tax_id_",
  "_national_id_",
  "_passport_number_",
  "_passport_",
  "_date_of_birth_",
  "_birth_date_",
  "_birthdate_",
  "_dob_",
];
const PII_REDACTION_MARKER = "[REDACTED]";

/** `stripeSecretKey`, `API-Key` and `first name` become `stripe_secret_key`, `api_key`, `first_name`. */
function normalizePiiKey(key: string): string {
  return key
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "_");
}

function isPiiKey(key: string): boolean {
  const normalized = normalizePiiKey(key);
  if (PII_KEYS.has(normalized)) return true;
  const padded = `_${normalized}_`;
  return PII_SEGMENTS.some((segment) => padded.includes(segment));
}

/** Recursively redacts known credential and direct-identifier fields. */
function sanitizePii(value: unknown): unknown {
  if (Array.isArray(value)) return value.map((item) => sanitizePii(item));
  if (value !== null && typeof value === "object") {
    const output: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value)) {
      output[key] = isPiiKey(key) ? PII_REDACTION_MARKER : sanitizePii(item);
    }
    return output;
  }
  return value;
}

const DEFAULT_TIMEOUT_MS = 30000;

let clientConfig: ClientConfig = { baseUrl: "" };

export function configureClient(config?: ClientConfig): ClientConfig {
  clientConfig = mergeConfig(clientConfig, config ?? {});
  return clientConfig;
}

export function getClientConfig(): ClientConfig {
  return clientConfig;
}

// ── Breadcrumbs + consent-gated context ────────────────────────────────────────
// The SDK keeps a rolling buffer of breadcrumbs (its own HTTP calls, plus
// anything the app records via addBreadcrumb) and, when the end user has granted
// consent, attaches the user + device/page context to each reported error.

const DEFAULT_MAX_BREADCRUMBS = 30;
let breadcrumbs: Breadcrumb[] = [];

/** Records a breadcrumb (navigation, click, log line, …) into the rolling buffer. */
export function addBreadcrumb(crumb: Breadcrumb): void {
  const max = clientConfig.logging?.maxBreadcrumbs ?? DEFAULT_MAX_BREADCRUMBS;
  breadcrumbs.push({ timestamp: new Date().toISOString(), ...crumb });
  if (breadcrumbs.length > max) breadcrumbs = breadcrumbs.slice(-max);
}

/** Clears the breadcrumb buffer (e.g. on logout or route change). */
export function clearBreadcrumbs(): void {
  breadcrumbs = [];
}

/** Sets the user attached to reported errors (only sent once consent is granted). */
export function setUser(user: Record<string, unknown> | undefined): void {
  clientConfig = mergeConfig(clientConfig, { logging: { user } });
}

/** Grants/revokes GDPR consent for sending the user + device/page context + breadcrumbs. */
export function setLoggingConsent(consent: boolean): void {
  clientConfig = mergeConfig(clientConfig, { logging: { consent } });
}

/**
 * Turns SDK logging on and configures it in one call.
 *
 * Logging is OFF by default — this SDK reports nothing until you ask it to.
 * There are exactly two ways to turn it on:
 *
 *   configureClient({ logging: { enabled: true } });   // at init
 *   setLoggingConfig({ environment: "production" });   // any time after
 *
 * Reports go to the endpoint this build was generated with, or to the
 * `endpoint` you pass; with neither, nothing is sent.
 *
 * Pass `{ enabled: false }` to turn logging back off. Any other field (endpoint,
 * apiKey, environment, release, tags, …) is merged over the current config.
 */
export function setLoggingConfig(config: LoggingConfig): void {
  // Opting in IS the point of this call, so `enabled` defaults to true here —
  // but an explicit `enabled: false` still wins, making this the off switch too.
  clientConfig = mergeConfig(clientConfig, {
    logging: { enabled: true, ...config },
  });
}

/** The logging config currently in effect (baked defaults + any overrides). */
export function getLoggingConfig(): LoggingConfig {
  return { ...DEFAULT_LOGGING, ...clientConfig.logging };
}

// Captures device/page context — browser-safe (guarded for non-DOM runtimes).
// `globalThis` is cast through `unknown` so this compiles whether or not the
// consumer's tsconfig includes the DOM lib.
function captureContext(): Record<string, unknown> {
  const g = globalThis as unknown as {
    navigator?: { userAgent?: string; language?: string; onLine?: boolean };
    screen?: { width?: number; height?: number };
    location?: { href?: string };
    document?: { title?: string; referrer?: string };
  };
  const ctx: Record<string, unknown> = {};
  if (g.navigator !== undefined) {
    ctx.device = {
      userAgent: g.navigator.userAgent,
      language: g.navigator.language,
      online: g.navigator.onLine,
      ...(g.screen !== undefined ? { screen: `${g.screen.width}x${g.screen.height}` } : {}),
    };
  }
  if (g.location !== undefined || g.document !== undefined) {
    ctx.page = {
      ...(g.location?.href !== undefined ? { url: g.location.href } : {}),
      ...(g.document?.referrer !== undefined && g.document.referrer !== ""
        ? { referrer: g.document.referrer }
        : {}),
      ...(g.document?.title !== undefined ? { title: g.document.title } : {}),
    };
  }
  return ctx;
}

export async function sdkRequest<T>(options: SdkRequestOptions): Promise<SdkResponse<T>> {
  const config = options.config ?? clientConfig;
  const retry: RetryConfig = { ...DEFAULT_RETRY, ...config.retry, ...options.retry };
  const idempotency: Required<IdempotencyConfig> = {
    ...DEFAULT_IDEMPOTENCY,
    ...config.idempotency,
  };
  const timeoutMs = options.timeoutMs ?? config.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const method = options.method.toUpperCase();
  const contentType = options.contentType ?? "application/json";
  const userMiddleware = config.middleware ?? [];
  const dispatch = composeMiddleware(userMiddleware, coreTransport);

  let idempotencyKey: string | null | undefined = options.idempotencyKey;
  if (idempotencyKey === undefined && idempotency.enabled && idempotency.methods.includes(method)) {
    idempotencyKey = generateIdempotencyKey();
  }

  const trace = { traceId: generateTraceId(), spanId: generateSpanId() };
  const spanStart = new Date().toISOString();

  for (let attempt = 1; attempt <= retry.maxAttempts; attempt += 1) {
    const headers: Record<string, string> = { ...config.auth?.headers, ...options.headers };
    const extraQuery: Record<string, string> = {};
    await applyAuth(config, headers, extraQuery, options.operationId);
    // For multipart, the runtime sets Content-Type (with the boundary) itself.
    // Only the encoder knows the boundary, so assigning the header here strips
    // it and every parser sees a body it cannot split.
    if (options.body !== undefined && !(contentType ?? "").startsWith("multipart/form-data")) {
      headers["Content-Type"] = contentType ?? "application/json";
    }
    if (idempotencyKey) headers[idempotency.headerName] = idempotencyKey;
    headers["traceparent"] = `00-${trace.traceId}-${trace.spanId}-01`;

    const url = buildUrl(config.baseUrl ?? "", options.path, options.query, extraQuery);
    const body = serializeBody(options.body, contentType);
    // A cancellation the caller raised before this attempt started never reaches
    // the transport at all.
    if (options.signal?.aborted) throw new SdkCancelledError(options.signal.reason);
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    // The caller's signal and the SDK deadline both abort this attempt; which one
    // fired decides the typed error the catch below raises.
    const onCallerAbort = () => controller.abort();
    options.signal?.addEventListener("abort", onCallerAbort, { once: true });
    const releaseSignal = () => options.signal?.removeEventListener("abort", onCallerAbort);
    const request: SdkRequest = {
      method,
      url,
      headers,
      body,
      operationId: options.operationId,
      attempt,
      signal: controller.signal,
      responseDecoder: options.responseDecoder ?? "json",
      meta: {},
    };

    try {
      const result = await dispatch(request);
      clearTimeout(timer);
      releaseSignal();

      if (result.statusCode >= 200 && result.statusCode < 300) {
        const typed = result as SdkResponse<T>;
        addBreadcrumb({
          type: "http",
          category: "http",
          level: "info",
          data: { method: options.method, url: options.path, status_code: result.statusCode },
        });
        logSpan(options, config, trace, spanStart, "ok");
        config.onResponse?.(typed);
        return typed;
      }

      if (
        attempt < retry.maxAttempts &&
        shouldRetryStatus(method, result.statusCode, retry.retryOn)
      ) {
        await sleep(
          computeBackoff(retry, attempt, result.headers["retry-after"] ?? null),
          options.signal,
        );
        continue;
      }

      const httpError = SdkHttpError.forStatus(
        result.statusCode,
        "",
        result.data,
        result.headers,
        result.requestId,
      );
      logSpan(options, config, trace, spanStart, "error");
      await logError(httpError, options, config, trace);
      addBreadcrumb({
        type: "http",
        category: "http",
        level: "error",
        data: { method: options.method, url: options.path, status_code: result.statusCode },
      });
      throw httpError;
    } catch (error) {
      clearTimeout(timer);
      releaseSignal();
      if (error instanceof SdkHttpError) throw error;
      // The caller's cancellation is their decision, not a transport failure:
      // it is never retried and never reported as the SDK's own timeout.
      if (error instanceof SdkCancelledError) throw error;
      if (options.signal?.aborted) throw new SdkCancelledError(options.signal.reason);

      const wrapped = isAbortError(error)
        ? new SdkTimeoutError(timeoutMs)
        : error instanceof SdkNetworkError || error instanceof SdkTimeoutError
          ? error
          : new SdkNetworkError(error);

      // See mayRepeatRequest: a failure with no response may not be blindly repeated.
      if (attempt < retry.maxAttempts && mayRepeatRequest(method, idempotencyKey)) {
        await sleep(computeBackoff(retry, attempt, null), options.signal);
        continue;
      }

      logSpan(options, config, trace, spanStart, "error");
      await logError(wrapped, options, config, trace);
      addBreadcrumb({
        type: "http",
        category: "http",
        level: "error",
        data: { method: options.method, url: options.path },
      });
      throw wrapped;
    }
  }

  // The loop body always returns or throws; this line is reachable only if
  // maxAttempts is misconfigured to 0.
  throw new SdkNetworkError(new Error(`Request '${options.operationId}' produced no attempts`));
}

export function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  if (signal?.aborted) return Promise.reject(new SdkCancelledError(signal.reason));
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      signal?.removeEventListener("abort", onAbort);
      resolve();
    }, ms);
    const onAbort = () => {
      clearTimeout(timer);
      reject(new SdkCancelledError(signal?.reason));
    };
    signal?.addEventListener("abort", onAbort, { once: true });
  });
}

/**
 * One Server-Sent Event yielded by `sdkStream`. The `data` field is parsed as
 * JSON when the value looks like JSON (`{...}` or `[...]`) and as the raw
 * string otherwise. Sentinel values like `[DONE]` arrive as strings so
 * consumers can terminate the stream explicitly.
 */
export interface SdkStreamEvent<T> {
  event: string;
  data: T;
  id: string | null;
  retry: number | null;
}

export interface SdkStreamOptions {
  method: string;
  path: string;
  query?: Record<string, unknown>;
  body?: unknown;
  headers?: Record<string, string>;
  contentType?: string;
  operationId: string;
  config?: ClientConfig;
  /** Aborts the underlying fetch and closes the stream. */
  signal?: AbortSignal;
  /**
   * Response framing. `sse` reads blank-line-delimited event records, `ndjson`
   * reads one complete JSON value per line, and `chunked` forwards each transport
   * chunk as it arrives with no record framing at all. Defaults to `sse` so an
   * existing caller is unaffected.
   */
  format?: "sse" | "ndjson" | "chunked";
  /** Declared response media type used for content negotiation. */
  accept?: string;
  /** For `chunked` only: whether a chunk is raw bytes or decoded text. */
  chunkDomain?: "bytes" | "text";
}

/**
 * Opens an SSE stream and yields parsed events. Bypasses the retry loop and
 * idempotency layer — streaming connections are long-lived and reconnect is
 * the consumer's responsibility. Auth is applied normally; user middleware
 * is not invoked because the response body is consumed incrementally.
 */
/**
 * The stream terminator convention SSE services use. Bracket-shaped, so the JSON
 * decoder has to know it is a sentinel rather than a malformed array.
 */
const STREAM_DONE_SENTINEL = "[DONE]";

const streamPayloadText = (payload: unknown): string => {
  if (typeof payload === "string") return payload;
  try {
    return JSON.stringify(payload) ?? String(payload);
  } catch {
    return String(payload);
  }
};

/**
 * Extracts a configured nested payload from an SSE or NDJSON event envelope.
 * Every generated streaming method shares this traversal so missing fields and
 * non-record intermediates fail consistently before wire-name remapping.
 */
export function unwrapStreamEvent(payload: unknown, eventField: readonly string[]): unknown {
  let current = payload;
  for (const segment of eventField) {
    // Arrays are valid JSON containers, so numeric eventField segments may
    // traverse them. Object.hasOwn keeps inherited names such as `constructor`
    // and `toString` out, while JSON-owned names such as `__proto__` remain
    // readable without ever mutating a prototype.
    if (current === null || typeof current !== "object") {
      throw new SdkStreamParseError(
        streamPayloadText(payload),
        undefined,
        null,
        "non-record-event-field",
        eventField,
      );
    }
    if (!Object.hasOwn(current, segment)) {
      throw new SdkStreamParseError(
        streamPayloadText(payload),
        undefined,
        null,
        "missing-event-field",
        eventField,
      );
    }
    current = (current as Record<string, unknown>)[segment];
  }
  return current;
}

export async function* sdkStream<T = unknown>(
  options: SdkStreamOptions,
): AsyncGenerator<SdkStreamEvent<T>> {
  const config = options.config ?? clientConfig;
  const method = options.method.toUpperCase();
  const headers: Record<string, string> = {
    ...config.auth?.headers,
    ...options.headers,
  };
  const extraQuery: Record<string, string> = {};
  await applyAuth(config, headers, extraQuery, options.operationId);
  if (options.body !== undefined) {
    const contentType = options.contentType ?? "application/json";
    // See the non-streaming path: multipart's boundary comes from the encoder.
    if (!contentType.startsWith("multipart/form-data")) {
      headers["Content-Type"] = contentType;
    }
  }
  const isNdjson = options.format === "ndjson";
  const isChunked = options.format === "chunked";
  headers["Accept"] =
    options.accept ??
    (isChunked
      ? "application/octet-stream"
      : isNdjson
        ? "application/x-ndjson"
        : "text/event-stream");
  const url = buildUrl(config.baseUrl ?? "", options.path, options.query, extraQuery);
  const body = serializeBody(options.body, options.contentType ?? "application/json");

  // A cancellation the caller raised before the stream opened never reaches the
  // transport, matching the non-streaming path.
  if (options.signal?.aborted) throw new SdkCancelledError(options.signal.reason);

  const response = await fetch(url, { method, headers, body, signal: options.signal });
  if (!response.ok || !response.body) {
    const respHeaders = collectHeaders(response);
    const requestId = findRequestId(respHeaders);
    const errBody = await parseResponseBody(response, "auto").catch(() => null);
    throw SdkHttpError.forStatus(
      response.status,
      response.statusText,
      errBody,
      respHeaders,
      requestId,
    );
  }

  const reader = response.body.getReader();

  // Fatal mode makes malformed or truncated UTF-8 an explicit stream failure.
  // The non-fatal default would silently replace bytes, and a missing final
  // decode would silently drop bytes held by the decoder at EOF.
  const decoder = new TextDecoder("utf-8", { fatal: true });
  let buffer = "";
  let eventName: string | null = null;
  let eventId: string | null = null;
  let eventRetry: number | null = null;
  let dataLines: string[] = [];

  // Chunked: the transport chunk IS the record. Nothing is split, joined, parsed
  // or buffered, because a raw stream's only structure is its boundaries and any
  // framing destroys them. Text chunks are decoded incrementally so a multi-byte
  // character split across a boundary is not corrupted; byte chunks are forwarded
  // untouched.
  const invalidUtf8 = (cause: unknown): SdkStreamParseError =>
    new SdkStreamParseError("", cause, null, "invalid-utf8");

  const decodeText = (value: Uint8Array, stream: boolean): string => {
    try {
      return decoder.decode(value, { stream });
    } catch (error) {
      throw invalidUtf8(error);
    }
  };

  const flushTextDecoder = (): string => {
    try {
      return decoder.decode();
    } catch (error) {
      throw invalidUtf8(error);
    }
  };

  const chunkEvent = (value: Uint8Array | string): SdkStreamEvent<T> => ({
    event: "message",
    data: (options.chunkDomain === "text"
      ? typeof value === "string"
        ? value
        : decodeText(value, true)
      : value) as T,
    id: null,
    retry: null,
  });

  // NDJSON: every non-empty line is one complete JSON value. A line that fails to
  // parse is a hard error rather than a silent passthrough, for the same reason as
  // in the SSE flush below -- the declared item type would otherwise be a lie.
  const decodeNdjsonLine = (line: string): SdkStreamEvent<T> | null => {
    const trimmed = line.trim();
    if (trimmed === "") return null;
    if (trimmed === STREAM_DONE_SENTINEL) return null;
    try {
      return { event: "message", data: JSON.parse(trimmed) as T, id: null, retry: null };
    } catch (error) {
      throw new SdkStreamParseError(trimmed, error);
    }
  };

  const flush = (): SdkStreamEvent<T> | null => {
    if (dataLines.length === 0) {
      eventName = null;
      return null;
    }
    const raw = dataLines.join("\n");
    let parsed: unknown = raw;
    const trimmed = raw.trim();
    // Only a JSON-shaped payload is decoded. SSE also carries bare text, so a
    // payload that never claimed to be an object is passed through untouched.
    if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
      try {
        parsed = JSON.parse(raw);
      } catch (error) {
        // "[DONE]" is bracket-shaped but is a terminator, not data — it is the
        // convention almost every SSE service ends with, and the generated method
        // returns on it. Everything else that claimed to be JSON and is not is an
        // error: handing back the raw text would make the operation's declared
        // event type a lie and move the failure somewhere the caller cannot
        // attribute it.
        if (trimmed !== STREAM_DONE_SENTINEL) {
          throw new SdkStreamParseError(raw, error);
        }
        parsed = raw;
      }
    }
    const ev: SdkStreamEvent<T> = {
      event: eventName ?? "message",
      data: parsed as T,
      id: eventId,
      retry: eventRetry,
    };
    eventName = null;
    dataLines = [];
    return ev;
  };

  try {
    while (true) {
      const { done, value } = await reader.read();

      if (done) {
        const finalText = flushTextDecoder();
        if (isChunked) {
          // A text chunk can leave a complete code point buffered while the
          // decoder waits for EOF. Preserve it as one final logical chunk;
          // byte chunks never touch the decoder and retain their exact source
          // boundaries and bytes.
          if (options.chunkDomain === "text" && finalText.length > 0) {
            yield chunkEvent(finalText);
          }
          return;
        }
        // SSE and NDJSON also need the decoder's final state appended before
        // their framing buffers are flushed. Fatal mode turns a truncated
        // trailing sequence into SdkStreamParseError instead of replacement
        // text or silent loss.
        buffer += finalText;
        if (isNdjson) {
          // A stream that ends without a trailing newline still has one record.
          const trailing = buffer.length > 0 ? decodeNdjsonLine(buffer) : null;
          buffer = "";
          if (trailing) yield trailing;
          return;
        }
        if (buffer.length > 0) {
          // Process any final trailing line.
          processSseLine(
            buffer,
            dataLines,
            (name) => {
              eventName = name;
            },
            (id) => {
              eventId = id;
            },
            (r) => {
              eventRetry = r;
            },
          );
          buffer = "";
        }
        const final = flush();
        if (final) yield final;
        return;
      }
      if (isChunked) {
        if (options.chunkDomain === "text") {
          // A decoder may hold the leading bytes of a split code point and
          // return an empty string for this transport chunk. That is decoder
          // state, not a real text chunk, so do not expose a synthetic event.
          const text = decodeText(value, true);
          if (text.length > 0) yield chunkEvent(text);
        } else {
          yield chunkEvent(value);
        }
        continue;
      }
      buffer += decodeText(value, true);
      // SSE spec: events are separated by blank lines; lines are separated by
      // \r\n, \r, or \n. Split on any of those, keep the trailing partial.
      const lines = buffer.split(/\r\n|\r|\n/);
      buffer = lines.pop() ?? "";
      for (const line of lines) {
        if (isNdjson) {
          // No record spans a line, so a complete line is a complete value. The
          // trailing partial stays in `buffer` and is carried to the next chunk.
          const ev = decodeNdjsonLine(line);
          if (ev) yield ev;
          continue;
        }
        if (line === "") {
          const ev = flush();
          if (ev) yield ev;
        } else {
          processSseLine(
            line,
            dataLines,
            (name) => {
              eventName = name;
            },
            (id) => {
              eventId = id;
            },
            (r) => {
              eventRetry = r;
            },
          );
        }
      }
    }
  } catch (error) {
    // The transport rejects an aborted read with the platform AbortError, which
    // a caller cannot tell apart from a network failure. Re-raise it as the same
    // typed cancellation the non-streaming path uses, so one `instanceof` works
    // for both. A parse error is already typed and passes through untouched.
    if (error instanceof SdkStreamParseError) throw error;
    if (options.signal?.aborted) throw new SdkCancelledError(options.signal.reason);
    throw error;
  } finally {
    try {
      reader.releaseLock();
    } catch {
      /* already released */
    }
  }
}

function processSseLine(
  line: string,
  dataLines: string[],
  setEvent: (name: string) => void,
  setId: (id: string) => void,
  setRetry: (retry: number) => void,
): void {
  if (line.startsWith(":")) return; // comment
  const colon = line.indexOf(":");
  const field = colon === -1 ? line : line.slice(0, colon);
  let value = colon === -1 ? "" : line.slice(colon + 1);
  if (value.startsWith(" ")) value = value.slice(1);
  switch (field) {
    case "event":
      setEvent(value);
      return;
    case "data":
      dataLines.push(value);
      return;
    case "id":
      setId(value);
      return;
    case "retry": {
      const n = Number.parseInt(value, 10);
      if (!Number.isNaN(n)) setRetry(n);
      return;
    }
  }
}

// Reports the client span for a settled request (fire-and-forget). Spans share
// the request's `traceId`; this client span is the root, and the backend's Octri
// package reports its server span as a child (via the propagated `traceparent`),
// so the dashboard can draw the request waterfall.
function logSpan(
  options: SdkRequestOptions,
  config: ClientConfig,
  trace: { traceId: string; spanId: string },
  startTime: string,
  status: "ok" | "error",
): void {
  const logging: LoggingConfig = { ...DEFAULT_LOGGING, ...config.logging };
  if (!logging.enabled || !logging.endpoint) return;
  const tracesUrl = logging.endpoint.replace(/\/ingest\/?$/, "/traces");
  const span: Record<string, unknown> = {
    traceId: trace.traceId,
    spanId: trace.spanId,
    name: `${options.method.toUpperCase()} ${options.path}`,
    service: "client",
    operationId: options.operationId,
    startTime,
    endTime: new Date().toISOString(),
    status,
  };
  if (logging.environment) span.environment = logging.environment;
  void postTelemetry(tracesUrl, logging.apiKey, span, logging.filterPii !== false).catch(() => {
    // Span reporting must never affect the request.
  });
}

/** POSTs a telemetry payload. Uses the same HTTP engine as the SDK itself so a
 * client never pulls in a second HTTP stack. */
async function postTelemetry(
  url: string,
  apiKey: string | undefined,
  payload: unknown,
  filterPii: boolean,
): Promise<void> {
  const headers = {
    "Content-Type": "application/json",
    ...(apiKey ? { Authorization: `Bearer ${apiKey}` } : {}),
  };

  await fetch(url, {
    method: "POST",
    headers,
    body: JSON.stringify(filterPii ? sanitizePii(payload) : payload),
  });
}

async function logError(
  error: SdkHttpError | SdkNetworkError | SdkTimeoutError,
  options: SdkRequestOptions,
  config: ClientConfig,
  trace?: { traceId: string; spanId: string },
): Promise<void> {
  const logging: LoggingConfig = { ...DEFAULT_LOGGING, ...config.logging };
  if (!logging.enabled || !logging.endpoint) return;
  // eventId lets the monitoring backend deduplicate retried deliveries; the rest
  // are enrichment fields it understands (level, stack, user/tags, etc.).
  const payload: Record<string, unknown> = {
    eventId: generateIdempotencyKey(),
    timestamp: new Date().toISOString(),
    level: "error",
    operationId: options.operationId,
    method: options.method,
    path: options.path,
    error: { name: error.name, message: error.message, stack: error.stack },
  };
  // Trace context — links this client error to the backend's server error.
  if (trace) {
    payload.traceId = trace.traceId;
    payload.spanId = trace.spanId;
  }
  if (error instanceof SdkHttpError) {
    payload.statusCode = error.statusCode;
  }
  if (error.requestId) payload.requestId = error.requestId;
  if (logging.environment) payload.environment = logging.environment;
  if (logging.release) payload.release = logging.release;
  if (logging.tags) payload.tags = logging.tags;
  // Personal data — the user, device/page context, and breadcrumbs — is only
  // sent once the end user has granted consent (GDPR-safe by default).
  if (logging.consent === true) {
    if (logging.user) payload.user = logging.user;
    const ctx = captureContext();
    if (Object.keys(ctx).length > 0) payload.context = ctx;
    if (breadcrumbs.length > 0) payload.breadcrumbs = breadcrumbs.slice();
  }
  try {
    await postTelemetry(logging.endpoint, logging.apiKey, payload, logging.filterPii !== false);
  } catch {
    // Logging failures must never mask the originating error.
  }
}

/**
 * Returned by paginated SDK methods when the generator emits in `paginator`
 * style. Supports lazy async iteration via `for await`, manual page navigation
 * via `nextPage()` / `previousPage()`, and collection via `toArray()`.
 *
 * Only the state fields relevant to the pagination type are populated at
 * runtime — `currentCursor` for cursor pagination, `currentOffset` / `total`
 * for offset, `currentPage` / `totalPages` for page-number, and `nextUrl` /
 * `previousUrl` for url-style follow links.
 */
export class Paginator<T> {
  hasMore: boolean = true;
  currentCursor?: string;
  currentOffset?: number;
  total?: number;
  currentPage?: number;
  totalPages?: number;
  nextUrl?: string;
  previousUrl?: string;

  private readonly _fetchNext: (state: Paginator<T>) => Promise<T[]>;
  private readonly _fetchPrev: ((state: Paginator<T>) => Promise<T[] | null>) | null;

  constructor(opts: {
    fetchNext: (state: Paginator<T>) => Promise<T[]>;
    fetchPrev?: (state: Paginator<T>) => Promise<T[] | null>;
    initialState?: Partial<Paginator<T>>;
  }) {
    if (opts.initialState) Object.assign(this, opts.initialState);
    this._fetchNext = opts.fetchNext;
    this._fetchPrev = opts.fetchPrev ?? null;
  }

  async nextPage(): Promise<T[]> {
    if (!this.hasMore) return [];
    return await this._fetchNext(this);
  }

  async previousPage(): Promise<T[] | null> {
    if (!this._fetchPrev) return null;
    return await this._fetchPrev(this);
  }

  async *[Symbol.asyncIterator](): AsyncIterator<T> {
    while (this.hasMore) {
      const items = await this.nextPage();
      if (items.length === 0) break;
      for (const item of items) yield item;
    }
  }

  async toArray(): Promise<T[]> {
    const all: T[] = [];
    for await (const item of this) all.push(item);
    return all;
  }
}

/** One typed response page emitted by a paginated operation's `...Pages` companion. */
export class SdkPage<TPage, TItem> {
  constructor(
    public readonly data: TPage,
    public readonly items: readonly TItem[],
    public readonly hasMore: boolean,
  ) {}
}
