// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

export type ValidationCode =
  | "enum"
  | "range"
  | "length"
  | "items"
  | "pattern"
  | "required"
  | "format:email"
  | "format:uri"
  | "format:uuid"
  | "format:date"
  | "format:date-time";

export interface ValidationMeta {
  allowed?: readonly unknown[];
  min?: number;
  max?: number;
  pattern?: string;
  exclusive?: { min?: boolean; max?: boolean };
}

export class SdkError extends Error {
  override name = "SdkError";

  constructor(message: string) {
    super(message);
  }
}

export class SdkValidationError extends SdkError {
  override name = "SdkValidationError";

  constructor(
    public readonly field: string,
    public readonly code: ValidationCode,
    message: string,
    public readonly meta: ValidationMeta = {},
  ) {
    super(message);
  }
}

export class SdkHttpError extends SdkError {
  override name = "SdkHttpError";

  constructor(
    public readonly statusCode: number,
    public readonly statusText: string,
    public readonly body: unknown,
    public readonly headers: Readonly<Record<string, string>>,
    public readonly requestId: string | null,
  ) {
    super(httpErrorMessage(statusCode, statusText, body, headers));
  }

  /** Builds the status-specific subclass, or the base class for other statuses. */
  static forStatus(
    statusCode: number,
    statusText: string,
    body: unknown,
    headers: Readonly<Record<string, string>>,
    requestId: string | null,
  ): SdkHttpError {
    const ErrorClass =
      statusCode >= 500 ? SdkInternalServerError : (STATUS_ERRORS[statusCode] ?? SdkHttpError);
    return new ErrorClass(statusCode, statusText, body, headers, requestId);
  }
}

export class SdkBadRequestError extends SdkHttpError {
  override name = "SdkBadRequestError";
}

export class SdkUnauthorizedError extends SdkHttpError {
  override name = "SdkUnauthorizedError";
}

export class SdkPermissionDeniedError extends SdkHttpError {
  override name = "SdkPermissionDeniedError";
}

export class SdkNotFoundError extends SdkHttpError {
  override name = "SdkNotFoundError";
}

export class SdkConflictError extends SdkHttpError {
  override name = "SdkConflictError";
}

export class SdkUnprocessableEntityError extends SdkHttpError {
  override name = "SdkUnprocessableEntityError";
}

export class SdkRateLimitError extends SdkHttpError {
  override name = "SdkRateLimitError";
}

/** Any 5xx response. */
export class SdkInternalServerError extends SdkHttpError {
  override name = "SdkInternalServerError";
}

const STATUS_ERRORS: Readonly<Record<number, typeof SdkHttpError>> = {
  400: SdkBadRequestError,
  401: SdkUnauthorizedError,
  403: SdkPermissionDeniedError,
  404: SdkNotFoundError,
  409: SdkConflictError,
  422: SdkUnprocessableEntityError,
  429: SdkRateLimitError,
};

const MAX_HTTP_ERROR_DETAIL_CODE_POINTS = 512;

function httpErrorMessage(
  statusCode: number,
  statusText: string,
  body: unknown,
  headers: Readonly<Record<string, string>>,
): string {
  const status = statusText ? `HTTP ${statusCode} ${statusText}` : `HTTP ${statusCode}`;
  const detail = httpErrorDetail(body, headers);
  return detail ? `${status}: ${detail}` : status;
}

/**
 * Returns a diagnostic string from response data only when it is an explicitly
 * supported error field or safe plain text. This keeps error messages useful
 * without dumping a complete response, which can carry credentials or markup.
 */
function httpErrorDetail(body: unknown, headers: Readonly<Record<string, string>>): string | null {
  const detail = objectErrorDetail(body);
  if (detail !== null) return detail;

  if (typeof body !== "string" || !allowsPlainTextErrorDetail(headers)) {
    return null;
  }
  return safeNormalizedHttpErrorDetail(body);
}

function objectErrorDetail(body: unknown): string | null {
  const nestedError = property(body, "error");
  const candidates = [
    stringProperty(body, "message"),
    stringProperty(body, "detail"),
    stringProperty(nestedError, "message"),
    stringProperty(nestedError, "detail"),
    typeof nestedError === "string" ? nestedError : null,
  ];
  for (const candidate of candidates) {
    if (candidate === null) continue;
    const normalized = safeNormalizedHttpErrorDetail(candidate);
    if (normalized !== null) return normalized;
  }
  return null;
}

function property(value: unknown, key: string): unknown {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return null;
  const descriptor = Object.getOwnPropertyDescriptor(value, key);
  return descriptor?.value ?? null;
}

function stringProperty(value: unknown, key: string): string | null {
  const candidate = property(value, key);
  return typeof candidate === "string" ? candidate : null;
}

function allowsPlainTextErrorDetail(headers: Readonly<Record<string, string>>): boolean {
  const contentType = headers["content-type"]?.split(";", 1)[0]?.trim().toLowerCase();
  return contentType === undefined || contentType.length === 0 || contentType.startsWith("text/");
}

function isPrintableHttpErrorText(value: string): boolean {
  for (const character of value) {
    if (character === "\t" || character === "\n" || character === "\r") continue;
    if (/\p{Cc}|\p{Cs}/u.test(character)) return false;
  }
  return true;
}

function safeNormalizedHttpErrorDetail(value: string): string | null {
  if (!isPrintableHttpErrorText(value)) return null;
  const normalized = value.replace(/\s+/gu, " ").trim();
  if (normalized.length === 0) return null;
  const characters = Array.from(normalized);
  if (characters.length <= MAX_HTTP_ERROR_DETAIL_CODE_POINTS) return normalized;
  return `${characters.slice(0, MAX_HTTP_ERROR_DETAIL_CODE_POINTS).join("")}…`;
}

export class SdkNetworkError extends SdkError {
  override name = "SdkNetworkError";

  public readonly cause: unknown;

  constructor(
    cause: unknown,
    public readonly requestId: string | null = null,
  ) {
    super(cause instanceof Error ? cause.message : String(cause));
    this.cause = cause;
  }
}

export class SdkTimeoutError extends SdkError {
  override name = "SdkTimeoutError";

  constructor(
    public readonly elapsedMs: number,
    public readonly requestId: string | null = null,
  ) {
    super(`Request timed out after ${elapsedMs}ms`);
  }
}

/**
 * A configured credential cannot be used as the scheme requires. The `code` is
 * the capability's canonical diagnostic identifier, so a caller can branch on
 * the specific defect rather than parsing the message.
 */
export class SdkCredentialError extends SdkError {
  override name = "SdkCredentialError";

  constructor(
    public readonly code: string,
    public readonly field: string,
    message: string,
  ) {
    super(message);
  }
}

/**
 * The operation requires authentication this package cannot supply: every
 * security alternative the specification offers names a scheme this build
 * exposes no credential for. The call is refused before it is dispatched rather
 * than sent unauthenticated for the server to reject.
 */
export class SdkAuthError extends SdkError {
  override name = "SdkAuthError";

  constructor(
    public readonly operationId: string,
    public readonly requiredSchemes: readonly string[],
  ) {
    super(
      `Operation ${operationId} requires authentication (${requiredSchemes.join(" or ")}), which this SDK cannot supply`,
    );
  }
}

/**
 * The configured OAuth 2 token provider could not supply a usable access token.
 * The provider's own failure, when there is one, is `cause`.
 */
export class SdkAuthProviderError extends SdkError {
  override name = "SdkAuthProviderError";

  public readonly cause: unknown;

  constructor(
    public readonly operationId: string | undefined,
    public readonly scheme: string,
    public readonly scopes: readonly string[],
    message: string,
    cause: unknown = undefined,
  ) {
    super(message);
    this.cause = cause;
  }
}

/**
 * The caller aborted the request through the `signal` it passed in. Distinct
 * from `SdkTimeoutError`, which the SDK raises on its own deadline: a
 * cancellation is the caller's decision, so it is never retried and carries the
 * caller's abort reason.
 */
export class SdkCancelledError extends SdkError {
  override name = "SdkCancelledError";

  public readonly cause: unknown;

  constructor(
    cause: unknown = undefined,
    public readonly requestId: string | null = null,
  ) {
    super("Request cancelled by the caller");
    this.cause = cause;
  }
}

/**
 * A long-running operation reached a state its descriptor lists as a failure.
 *
 * Distinct from `SdkNetworkError`, which is what this used to be: nothing went wrong
 * with the request. The service answered, and its answer was that the operation will
 * not complete. A caller retrying a dropped connection and a caller reporting a failed
 * job are doing different things, so they need different types. The terminal state is
 * carried verbatim, because it is the only thing that says *why*.
 */
export class SdkOperationFailedError extends SdkError {
  override name = "SdkOperationFailedError";

  constructor(public readonly state: string | undefined) {
    super(`Operation failed in state ${state ?? "unknown"}`);
  }
}

/**
 * A streamed record could not be decoded into its declared event type.
 *
 * The alternative was handing back the raw text, which is worse than an error:
 * the operation's signature promises a parsed event, so a silent fallback makes
 * the type a lie and moves the failure somewhere the caller cannot attribute it.
 * The offending payload is carried verbatim so a caller can log or inspect what
 * the service actually sent.
 */
export class SdkStreamParseError extends SdkError {
  override name = "SdkStreamParseError";

  public readonly cause: unknown;

  constructor(
    public readonly payload: string,
    cause: unknown = undefined,
    public readonly requestId: string | null = null,
    public readonly reason:
      | "invalid-json"
      | "missing-event-field"
      | "non-record-event-field"
      | "invalid-utf8" = "invalid-json",
    public readonly eventField: readonly string[] | null = null,
  ) {
    super(
      reason === "invalid-json"
        ? "Malformed streamed event: the payload is not valid JSON"
        : reason === "missing-event-field"
          ? `Malformed streamed event: event field '${eventField?.join(".") ?? ""}' is absent`
          : reason === "non-record-event-field"
            ? `Malformed streamed event: event field '${eventField?.join(".") ?? ""}' crosses a non-record value`
            : "Malformed streamed event: the payload is not valid UTF-8",
    );
    this.cause = cause;
  }
}
