// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type * as Types from "./types";
import { fromWire, toWire } from "./client";

import { validateDate } from "./validation";

type RuntimeRecord = Record<string, unknown>;

interface RuntimeSchema {
  ref?: string;
  type?: string | readonly string[];
  nullable?: boolean;
  enum?: readonly unknown[];
  required?: readonly string[];
  properties?: Readonly<Record<string, RuntimeSchema>>;
  items?: RuntimeSchema;
  additionalProperties?: RuntimeSchema;
  oneOf?: readonly RuntimeSchema[];
  anyOf?: readonly RuntimeSchema[];
  allOf?: readonly RuntimeSchema[];
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number | boolean;
  exclusiveMaximum?: number | boolean;
  multipleOf?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  pattern?: string;
  format?: "email" | "uri" | "uuid" | "date" | "date-time";
}

const modelSchemas: Readonly<Record<string, RuntimeSchema>> = {
  ModelsSummary: {
    type: "object",
    properties: {
      branches: { type: "array", items: { ref: "ModelsSummaryItem" } },
      categories: { type: "array", items: { ref: "ModelsSummaryItem" } },
      editors: { type: "array", items: { ref: "ModelsSummaryItem" } },
      entities: { type: "array", items: { ref: "ModelsSummaryItem" } },
      from: { type: "string", format: "date" },
      labels: { type: "array", items: { ref: "ModelsSummaryItem" } },
      languages: { type: "array", items: { ref: "ModelsSummaryItem" } },
      machines: { type: "array", items: { ref: "ModelsSummaryItem" } },
      operatingSystems: { type: "array", items: { ref: "ModelsSummaryItem" } },
      projects: { type: "array", items: { ref: "ModelsSummaryItem" } },
      to: { type: "string", format: "date" },
      userId: { type: "string" },
    },
  },
};

const isRecord = (value: unknown): value is RuntimeRecord =>
  value !== null && typeof value === "object" && !Array.isArray(value);

const childField = (field: string, property: string): string =>
  field ? `${field}.${property}` : property;

const hasType = (schema: RuntimeSchema, type: string): boolean =>
  schema.type === type || (Array.isArray(schema.type) && schema.type.includes(type));

const allowsNull = (schema: RuntimeSchema | undefined, seen = new Set<string>()): boolean => {
  if (!schema) return false;
  if (schema.nullable === true || hasType(schema, "null")) return true;
  if (!schema.ref || seen.has(schema.ref)) return false;
  seen.add(schema.ref);
  const referenced = modelSchemas[schema.ref];
  return referenced ? allowsNull(referenced, seen) : false;
};

const validateNode = (value: unknown, schema: RuntimeSchema, field: string): unknown => {
  if (schema.ref) {
    const referenced = modelSchemas[schema.ref];
    return referenced ? validateNode(value, referenced, field) : value;
  }

  if (value === null) {
    if (schema.nullable === true || hasType(schema, "null")) return value;
    return value;
  }

  if (schema.allOf) {
    for (const member of schema.allOf) validateNode(value, member, field);
  }

  if (schema.oneOf || schema.anyOf) {
    const members = schema.oneOf ?? schema.anyOf ?? [];
    let firstError: unknown;
    for (const member of members) {
      try {
        return validateNode(value, member, field);
      } catch (error) {
        firstError ??= error;
      }
    }
    if (firstError instanceof Error) throw firstError;
  }

  if (hasType(schema, "object") || schema.properties) {
    if (!isRecord(value)) return value;
    for (const property of schema.required ?? []) {
      const propertyValue = value[property];
      const propertySchema = schema.properties?.[property];
      const missing =
        !Object.prototype.hasOwnProperty.call(value, property) || propertyValue === undefined;
      const invalidNull = propertyValue === null && !allowsNull(propertySchema);
      if (missing || invalidNull) {
      }
    }
    for (const [property, propertySchema] of Object.entries(schema.properties ?? {})) {
      if (Object.prototype.hasOwnProperty.call(value, property)) {
        validateNode(value[property], propertySchema, childField(field, property));
      }
    }
    if (schema.additionalProperties) {
      for (const [property, propertyValue] of Object.entries(value)) {
        if (!(property in (schema.properties ?? {}))) {
          validateNode(propertyValue, schema.additionalProperties, childField(field, property));
        }
      }
    }
  }

  if (hasType(schema, "array")) {
    if (!Array.isArray(value)) return value;
    if (schema.items) {
      value.forEach((item, index) =>
        validateNode(item, schema.items as RuntimeSchema, childField(field, String(index))),
      );
    }
  }

  if (schema.format === "date") validateDate(field, value as string);

  return value;
};

const validateModel = <T>(value: T, typeName: string): T => {
  const schema = modelSchemas[typeName];
  return schema ? (validateNode(value, schema, "") as T) : value;
};

export const modelConstructionStyle = "typed-record" as const;

/** Constructs a validated ModelsDiagnostics model value. */
export function createModelsDiagnostics(value: Types.ModelsDiagnostics): Types.ModelsDiagnostics {
  return validateModel({ ...value }, "ModelsDiagnostics");
}

/** Constructs a validated ModelsHeartbeat model value. */
export function createModelsHeartbeat(value: Types.ModelsHeartbeat): Types.ModelsHeartbeat {
  return validateModel({ ...value }, "ModelsHeartbeat");
}

/** Constructs a validated ModelsSummary model value. */
export function createModelsSummary(value: Types.ModelsSummary): Types.ModelsSummary {
  return validateModel({ ...value }, "ModelsSummary");
}

/** Constructs a validated ModelsSummaryItem model value. */
export function createModelsSummaryItem(value: Types.ModelsSummaryItem): Types.ModelsSummaryItem {
  return validateModel({ ...value }, "ModelsSummaryItem");
}

/** Constructs a validated V1AllTimeData model value. */
export function createV1AllTimeData(value: Types.V1AllTimeData): Types.V1AllTimeData {
  return validateModel({ ...value }, "V1AllTimeData");
}

/** Constructs a validated V1AllTimeRange model value. */
export function createV1AllTimeRange(value: Types.V1AllTimeRange): Types.V1AllTimeRange {
  return validateModel({ ...value }, "V1AllTimeRange");
}

/** Constructs a validated V1AllTimeViewModel model value. */
export function createV1AllTimeViewModel(
  value: Types.V1AllTimeViewModel,
): Types.V1AllTimeViewModel {
  return validateModel({ ...value }, "V1AllTimeViewModel");
}

/** Constructs a validated V1BadgeData model value. */
export function createV1BadgeData(value: Types.V1BadgeData): Types.V1BadgeData {
  return validateModel({ ...value }, "V1BadgeData");
}

/** Constructs a validated V1HeartbeatEntry model value. */
export function createV1HeartbeatEntry(value: Types.V1HeartbeatEntry): Types.V1HeartbeatEntry {
  return validateModel({ ...value }, "V1HeartbeatEntry");
}

/** Constructs a validated V1HeartbeatsResult model value. */
export function createV1HeartbeatsResult(
  value: Types.V1HeartbeatsResult,
): Types.V1HeartbeatsResult {
  return validateModel({ ...value }, "V1HeartbeatsResult");
}

/** Constructs a validated V1LeadersCurrentUser model value. */
export function createV1LeadersCurrentUser(
  value: Types.V1LeadersCurrentUser,
): Types.V1LeadersCurrentUser {
  return validateModel({ ...value }, "V1LeadersCurrentUser");
}

/** Constructs a validated V1LeadersEntry model value. */
export function createV1LeadersEntry(value: Types.V1LeadersEntry): Types.V1LeadersEntry {
  return validateModel({ ...value }, "V1LeadersEntry");
}

/** Constructs a validated V1LeadersLanguage model value. */
export function createV1LeadersLanguage(value: Types.V1LeadersLanguage): Types.V1LeadersLanguage {
  return validateModel({ ...value }, "V1LeadersLanguage");
}

/** Constructs a validated V1LeadersRange model value. */
export function createV1LeadersRange(value: Types.V1LeadersRange): Types.V1LeadersRange {
  return validateModel({ ...value }, "V1LeadersRange");
}

/** Constructs a validated V1LeadersRunningTotal model value. */
export function createV1LeadersRunningTotal(
  value: Types.V1LeadersRunningTotal,
): Types.V1LeadersRunningTotal {
  return validateModel({ ...value }, "V1LeadersRunningTotal");
}

/** Constructs a validated V1LeadersViewModel model value. */
export function createV1LeadersViewModel(
  value: Types.V1LeadersViewModel,
): Types.V1LeadersViewModel {
  return validateModel({ ...value }, "V1LeadersViewModel");
}

/** Constructs a validated V1Project model value. */
export function createV1Project(value: Types.V1Project): Types.V1Project {
  return validateModel({ ...value }, "V1Project");
}

/** Constructs a validated V1ProjectViewModel model value. */
export function createV1ProjectViewModel(
  value: Types.V1ProjectViewModel,
): Types.V1ProjectViewModel {
  return validateModel({ ...value }, "V1ProjectViewModel");
}

/** Constructs a validated V1ProjectsViewModel model value. */
export function createV1ProjectsViewModel(
  value: Types.V1ProjectsViewModel,
): Types.V1ProjectsViewModel {
  return validateModel({ ...value }, "V1ProjectsViewModel");
}

/** Constructs a validated V1StatsData model value. */
export function createV1StatsData(value: Types.V1StatsData): Types.V1StatsData {
  return validateModel({ ...value }, "V1StatsData");
}

/** Constructs a validated V1StatsViewModel model value. */
export function createV1StatsViewModel(value: Types.V1StatsViewModel): Types.V1StatsViewModel {
  return validateModel({ ...value }, "V1StatsViewModel");
}

/** Constructs a validated V1StatusBarViewModel model value. */
export function createV1StatusBarViewModel(
  value: Types.V1StatusBarViewModel,
): Types.V1StatusBarViewModel {
  return validateModel({ ...value }, "V1StatusBarViewModel");
}

/** Constructs a validated V1SummariesCumulativeTotal model value. */
export function createV1SummariesCumulativeTotal(
  value: Types.V1SummariesCumulativeTotal,
): Types.V1SummariesCumulativeTotal {
  return validateModel({ ...value }, "V1SummariesCumulativeTotal");
}

/** Constructs a validated V1SummariesDailyAverage model value. */
export function createV1SummariesDailyAverage(
  value: Types.V1SummariesDailyAverage,
): Types.V1SummariesDailyAverage {
  return validateModel({ ...value }, "V1SummariesDailyAverage");
}

/** Constructs a validated V1SummariesData model value. */
export function createV1SummariesData(value: Types.V1SummariesData): Types.V1SummariesData {
  return validateModel({ ...value }, "V1SummariesData");
}

/** Constructs a validated V1SummariesEntry model value. */
export function createV1SummariesEntry(value: Types.V1SummariesEntry): Types.V1SummariesEntry {
  return validateModel({ ...value }, "V1SummariesEntry");
}

/** Constructs a validated V1SummariesGrandTotal model value. */
export function createV1SummariesGrandTotal(
  value: Types.V1SummariesGrandTotal,
): Types.V1SummariesGrandTotal {
  return validateModel({ ...value }, "V1SummariesGrandTotal");
}

/** Constructs a validated V1SummariesRange model value. */
export function createV1SummariesRange(value: Types.V1SummariesRange): Types.V1SummariesRange {
  return validateModel({ ...value }, "V1SummariesRange");
}

/** Constructs a validated V1SummariesViewModel model value. */
export function createV1SummariesViewModel(
  value: Types.V1SummariesViewModel,
): Types.V1SummariesViewModel {
  return validateModel({ ...value }, "V1SummariesViewModel");
}

/** Constructs a validated V1User model value. */
export function createV1User(value: Types.V1User): Types.V1User {
  return validateModel({ ...value }, "V1User");
}

/** Constructs a validated V1UserAgentEntry model value. */
export function createV1UserAgentEntry(value: Types.V1UserAgentEntry): Types.V1UserAgentEntry {
  return validateModel({ ...value }, "V1UserAgentEntry");
}

/** Constructs a validated V1UserAgentsViewModel model value. */
export function createV1UserAgentsViewModel(
  value: Types.V1UserAgentsViewModel,
): Types.V1UserAgentsViewModel {
  return validateModel({ ...value }, "V1UserAgentsViewModel");
}

/** Constructs a validated V1UserViewModel model value. */
export function createV1UserViewModel(value: Types.V1UserViewModel): Types.V1UserViewModel {
  return validateModel({ ...value }, "V1UserViewModel");
}

/** Serializes a constructed model using the generated wire-name mapping. */
export function serializeModel<T>(value: T, typeName: string): unknown {
  return toWire(validateModel(value, typeName), typeName);
}

/** Decodes and validates a wire model through the generated public surface. */
export function deserializeModel<T>(value: unknown, typeName: string): T {
  return validateModel<T>(fromWire(value, typeName) as T, typeName);
}
