// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { SdkValidationError } from "./errors";

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
export function validateDate(field: string, value: string | Date): void {
  // `date`-format values are typed as the wire string; an untyped caller may
  // still pass a `Date`, which the client serializes to YYYY-MM-DD.
  const asString = value instanceof Date ? value.toISOString().slice(0, 10) : value;
  if (!DATE_RE.test(asString) || Number.isNaN(Date.parse(asString))) {
    throw new SdkValidationError(
      field,
      "format:date",
      `Validation failed for '${field}': must be a valid date (YYYY-MM-DD)`,
    );
  }
}
