// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, LoggingConfig } from "./client";
import { BadgesNamespace } from "./methods/badges";
import { WakatimeNamespace } from "./methods/wakatime";
import { HeartbeatNamespace } from "./methods/heartbeat";
import { MiscNamespace } from "./methods/misc";
import { DiagnosticsNamespace } from "./methods/diagnostics";
import { SummaryNamespace } from "./methods/summary";

export class Wakapi {
  private readonly _config: ClientConfig;
  readonly badges: BadgesNamespace;
  readonly wakatime: WakatimeNamespace;
  readonly heartbeat: HeartbeatNamespace;
  readonly misc: MiscNamespace;
  readonly diagnostics: DiagnosticsNamespace;
  readonly summary: SummaryNamespace;

  constructor(config: ClientConfig) {
    this._config = config;
    this.badges = new BadgesNamespace(config);
    this.wakatime = new WakatimeNamespace(config);
    this.heartbeat = new HeartbeatNamespace(config);
    this.misc = new MiscNamespace(config);
    this.diagnostics = new DiagnosticsNamespace(config);
    this.summary = new SummaryNamespace(config);
  }

  /**
   * Turns SDK logging on and configures it. Logging is OFF by default — this
   * SDK reports nothing until you call this (or construct the client with
   * `logging: { enabled: true }`). Reports go to the endpoint this build was
   * generated with, or to the `endpoint` you pass; with neither, nothing is sent.
   * Pass `{ enabled: false }` to turn it off.
   */
  setLoggingConfig(config: LoggingConfig): void {
    this._config.logging = { ...this._config.logging, enabled: true, ...config };
  }
}
